### ISSUE TITLE
Show duplicate app when with google account by auth0 

### ISSUE THREAD

**Issue by lehuydev2203** [auth0/react-native-auth0#536] opened 2022-10-17 09:56 UTC
Hi, 
I use react-native-auth0 version 2.13.3. When I log in with a google account, after I choose an account, have a popup showing 'open with ... ' with 2 applications but only the app can log in, remaining to fail.

![photo_2022-10-17_16-55-17](https://user-images.githubusercontent.com/41155784/196148237-3dc7afd8-8300-4ac3-8a82-766d979c4ba4.jpg)

**Comment by poovamraj** [comment] 2022-10-17 10:18
Hi, can you run this command and see what are all the intent receivers you have for your package name - `adb shell dumpsys package r`. They can be in different locations so it would be great to comb through them or grep them

**Comment by lehuydev2203** [comment] 2022-10-18 02:38
> 

I can't run login google on adb and my stuck by a real device

**Comment by poovamraj** [comment] 2022-10-18 08:28
@mailaneel Can you verify the above command doesn't generate 2 different intent receivers for your application id. 

Can you also verify that the changes are the ones that are available in the app? Yarn has complicated cache management and wouldn't install the new package if the version number is same. I'd recommend to check if `node_modules` have the diff reflected

**Comment by mailaneel** [comment] 2022-10-18 08:49
@poovamraj 
1. It does generate 2 intent receivers one for RedirectActivity and on for MainActivity
2. Yes I have verified node_modules to see the changes are reflected from your commit

I see below

```
        <activity
            android:name="com.auth0.android.provider.RedirectActivity"
            tools:node="remove"/>

        <activity
            android:name="com.auth0.android.provider.AuthenticationActivity"
            tools:node="remove"/>
```

auth0 intent filter's looks like this
```
        <activity
            android:name="com.auth0.react.RedirectActivity"
            android:exported="true">
            <intent-filter android:autoVerify="true"
                tools:targetApi="m">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                 <data
                    android:host="${auth0Domain}"
                    android:path="/android/${applicationId}/callback"
                    android:scheme="${auth0Scheme}" />
            </intent-filter>
        </activity>
```

our one looks like this

```
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="${applicationId}"/>
      </intent-filter>
```

Both are using same scheme and both matches one with prefix filter and one without prefix filter so seeing prompt

**Comment by mailaneel** [comment] 2022-10-18 08:53
Before adding your PR change, I was seeing 3, one of them `com.auth0.android.provider.RedirectActivity`

![Screen Shot 2022-10-18 at 7 51 34 pm](https://user-images.githubusercontent.com/129355/196384193-7d4f6221-b0ca-4f56-bb67-c9af32714b5c.png)

**Comment by poovamraj** [comment] 2022-10-18 09:03
Yep, that seems right, with the PR change there should only be 2. One is the launcher intent receiver and the other one is for our callback

So the issue is being reproduced in this scenario as well? That should be highly unlikely since we have only 1 intent receiver for URLs

**Comment by mailaneel** [comment] 2022-10-18 09:09
yes its is reproducible unfortunately

**Comment by mailaneel** [comment] 2022-10-18 09:37
I have added the below change to our manifest file(pathPrefix) and it seems now I am not seeing the prompt anymore:
```
<data android:scheme="${applicationId}" android:pathPrefix="/" />
```

I will confirm after more tests

**Comment by poovamraj** [comment] 2022-10-18 09:49
Ah okay, I didn'tt realize you had a intent receiver as well. My bad. Great the issue is not occuring now.

**Comment by mailaneel** [comment] 2022-10-18 09:52
sorry posted early, its still happening any help would be appreciated

**Comment by poovamraj** [comment] 2022-10-18 09:56
Hi @mailaneel I'd suggest the following to avoid this issue. This is happening because your intent receiver is a catch-all and seems to interfere with the Authentication callback

1. Use a different `scheme` for authentication or your login. 
2. Specify the exact `android:pathPrefix` for which you want to open your app. Now it will open for all links which has the `scheme` that is your `application_id`

**Comment by poovamraj** [comment] 2022-10-18 17:35
Hi @mailaneel @lehuydev2203 hope this answers your questions. I will close this issue for now, please feel free to reopen this if you have more doubts

**Closed by poovamraj** 2022-10-18 17:35 UTC
Labels: question

**Comment by AndonMitev** [comment] 2022-12-10 08:16
He guys, can i use this thread because i have the exact similar problem. So in `Callback URLS` i do have just 1 for my application but then this modal `Open with` pop up and it has 2 times the application just like on the screenshot above. So from this suggestion  https://github.com/auth0/react-native-auth0/issues/536#issuecomment-1282134579 1. is true but should i do 2. if i have unique scheme and still see open with twice with my app?

**Comment by poovamraj** [comment] 2022-12-12 11:54
@AndonMitev did you try using the command mentioned here - https://github.com/auth0/react-native-auth0/issues/536#issuecomment-1280627909 to try and debug which activity is causing this?

**Comment by AndonMitev** [comment] 2022-12-12 11:55
@poovamraj Yes, let me share results
