### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME in some devices

### ISSUE THREAD

**Issue by MatiAedo** [auth0/react-native-auth0#484] opened 2022-06-15 16:59 UTC
### The problem

Hello, we are working in a mobile app with react native including auth0. We have setted the sdk following this [tutorial](https://auth0.com/docs/quickstart/native/react-native/00-login?_ga=2.203791829.499200059.1655271560-439011996.1650323642&_gl=1*f3ox60*rollup_ga*NDM5MDExOTk2LjE2NTAzMjM2NDI.*rollup_ga_F1G3E656YZ*MTY1NTMxMDQ1My4xMC4wLjE2NTUzMTA0NTMuNjA.#native-configuration) and it works in the emulator and most of devices we tested, but crashes in some devices when we try to log in. It inmediatly redirects to another generic page (telephone company) or show the error ERR_UNKNOWN_URL_SCHEME instead the login service from auth0.  I have checked this similiar [issue](https://github.com/auth0/react-native-auth0/issues/481) but those files are right.

### What was the expected behavior?

It inmediatly redirects to another generic page (telephone company) or show the error ERR_UNKNOWN_URL_SCHEME instead the login service from auth0.  I have checked this similiar [issue](https://github.com/auth0/react-native-auth0/issues/481) but those files are right.

### Files

build.gradle:

    defaultConfig {

        applicationId "com.myapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 11
        versionName "0.0.1"
        manifestPlaceholders = [auth0Domain: "dev-85b-8c8t.us.auth0.com", auth0Scheme: "${applicationId}"]
    }

AndroidManifest.xml:

       <activity
            android:name="com.auth0.react.AuthenticationActivity"
            android:exported="false"
            android:launchMode="singleTask"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />
        <activity
            android:name="com.auth0.react.RedirectActivity"
            android:exported="true" >
            <intent-filter android:autoVerify="true" >
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="dev-85b-8c8t.us.auth0.com"
                    android:pathPrefix="/android/com.myapp/callback"
                    android:scheme="com.myapp" />
            </intent-filter>
        </activity>

### Environment
Android
"react": "17.0.2"
"react-native": "0.67.3"
"react-native-auth0": "^2.13.1"

**Comment by poovamraj** [comment] 2022-06-16 10:51
Hi @MatiAedo, can you let us know which devices are causing this issue, Android and Chrome version in which the issue is happening?

**Comment by MatiAedo** [comment] 2022-06-18 04:06
Hi @poovamraj ! Sorry for the delay
We are asking our clients those details, but until now only one answered. It is a Huawei with Emui 12.0.0 (Android 11) and Huawei Webview 11.1.5.315. Also we know that there are some Samsung devices and we are waiting for the details. In our team we tested two Xiaomi and one Motorola with the latest versions of Chrome/Webview and it works perfectly. When I know the details of the other devices, I'll let you know (I hope during this weekend)

**Comment by poovamraj** [comment] 2022-07-22 07:49
Hi @MatiAedo, were you able to get more device information? we are not able to reproduce this issue from our end. It would be great if you can provide an environment where we can reproduce this.

**Comment by MatiAedo** [comment] 2022-07-26 02:11
Hi @poovamraj ! Sorry again for being late reply. Finally it worked on all the devices, we didn't make any changes so we supposed that it was a problem with some versions of Chrome/WebView, or maybe a change in the library. I'm so thankful for your fast answers!

**Comment by poovamraj** [comment] 2022-07-26 12:31
Thanks a lot @MatiAedo! that sounds wonderful. We will close this issue for now. Please feel to reopen it if you have any more doubts!

**Closed by poovamraj** 2022-07-26 12:31 UTC
Labels: waiting for customer
