### ISSUE TITLE
Stuck at log in after entering credentials on Android, doesn't redirect back or log me in

### ISSUE THREAD

**Issue by ttlenell** [auth0/react-native-auth0#606] opened 2023-03-24 14:34 UTC
### Describe the problem

Issues with loggin in with an android device / simulator. After entering the credentials in the browser that appears, I press "Continue" and I see in the top of my browser that it tries to load the request but stops loading after about one second and then nothing happens. Nothing happens if I press the "Continue"-button either. 

But this only happens when I enter the correct credentials. If I enter the wrong ones on purpose, it will give me an error that its wrong. 

And when I press back/exit the browser to return to the app to try again, the browser just stays blank. Nothing happens and I can't trigger anything. 

This ONLY happens on android, iOS works just fine.

### What was the expected behavior?

Be able to log in without issue on android. After I've put in credentials and pressed "Continue", it should redirect me back to app and I should be logged in.

### Reproduction
Set up a new expo project with Typescript and the latest SDK.
Add `react-native-auth0` & `@types/react-native-auth0`.

Copy the example code detailed here for example
https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Expo

### Environment

react-native-auth0@2.17.1
@types/react-native-auth0@2.14.1
react-native@0.71.4
expo@48.0.9

react-native info:

```
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 129.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 26, 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Please let me know if there's any other information I can provide.

**Comment by ttlenell** [comment] 2023-03-27 12:41
Alright so figured out that it's related to my package name not being all in lowercase.
My package name (just an example): com.company.Appname when it should've been just com.company.appname.

When I change the package name locally to lowercase and whitelist the lowercase version, it works. But I can't do that since the existing users have an app out that its based on "Appname" and that is working with an older version of auth0. 

It seems that the package has issues trying to redirect me back to the app since package names isn't matching.

**Comment by poovamraj** [comment] 2023-03-27 14:25
@ttlenell is the old SDK working with the `com.company.Appname` as callback URL?

**Comment by poovamraj** [comment] 2023-03-31 17:18
Hi @ttlenell, we have made few changes to the documentation that will avoid the confusion. The PRs to the docs are here

https://github.com/auth0/react-native-auth0/pull/610
https://github.com/auth0-samples/auth0-react-native-sample/pull/113

Please feel free to provide your feedback there. Closing this issue in favour of the PRs. But feel free to comment here if you have more to add and we can reopen this issue.

**Closed by poovamraj** 2023-03-31 17:18 UTC
Labels: question

**Comment by ttlenell** [comment] 2023-04-05 09:25
Sure! @poovamraj 

This is the warning I get when trying to log in on my android emulator:
` WARN  The Bundle Identifier or Application ID of your app contains uppercase characters and will be lowercased to build the Callback URL. Check the Auth0 dashboard to whitelist the right URL value.`
The warning shows up on iOS as well but on iOS it works without issue.

These are my callbacks from the auth0 dashboard, swapped the real appName to "App". 

auth/index.tsx
`// AUTH0:INSTANCE
export const auth0Instance = async () => {
  const clientId = storage.getString(Constants.CLIENT_ID);
  if (clientId) {
    const auth0 = new Auth0({
      domain: Constants.AUTH0_URL,
      clientId,
    });

    return auth0;
  }
};

// AUTH0:LOGIN
export const auth0Login = async () => {
  let loggedIn = false;
  let data;
  try {
    const organizationId = storage.getString(Constants.ORGANIZATION_ID);
    const auth0 = await auth0Instance();

    if (auth0) {
      data = await auth0.webAuth.authorize(
        {
          scope: 'openid profile email offline_access',
          organization: organizationId,
          audience: Constants.AUTH0_AUDIENCE,
        },
        { ephemeralSession: true, customScheme: 'se.staylive.App' },
      );
      loggedIn = true;
      storage.set('accessToken', data.accessToken);
      if (data.refreshToken) {
        storage.set('refreshToken', data.refreshToken);
      }
    }
    return { data, loggedIn, error: '' };
  } catch (err) {
    console.log('auth0Login: Error', err);
  }
};`
app.config.js
`plugins: [
 .....
    [
      'react-native-auth0',
      {
        domain: 'staylive.eu.auth0.com',
        customScheme: 'se.staylive.App',
      },
    ],
    ]`
    
    Here's what happens when i try to log in:
    
    I get to browser, see the correct app-logo and can type my credentials. If they are wrong, i'll get an error. If they are correct, I can see that it's loading for a few seconds but it can't redirect me back to the app. If I then go back and want to try again, I get stuck at a white background in the browser and nothing happens. 
    
    I'm really hoping that i'm missing something simple here haha. 
    Appreciate your help!

**Comment by poovamraj** [comment] 2023-04-05 12:11
@ttlenell as you can see you are using the `App` in your `customScheme` which is doesn't have a lowercase "A" in it. That is  the reason you are getting the redirection warning and the user cancellation error.

**Comment by ttlenell** [comment] 2023-04-05 13:01
> @ttlenell as you can see you are using the `App` in your `customScheme` which doesn't have a lowercase "A" in it. That is the reason you are getting the redirection warning and the user cancellation error.

Hi again @poovamraj 

Yes, I've tried that and no progress. Right now my code looks like this:

```
  data = await auth0.webAuth.authorize(
        {
          scope: 'openid profile email offline_access',
          organization: organizationId,
          audience: Constants.AUTH0_AUDIENCE,
        },
        { ephemeralSession: true, customScheme: 'se.staylive.app' },
      );
```

app.config.js
```
plugins: [
 .....
    [
      'react-native-auth0',
      {
        domain: 'staylive.eu.auth0.com',
        customScheme: 'se.staylive.app',
      },
    ],
    ]
```

I even tried having one as App and the other as app (and tried the other way around as well).

Could it be related to this in `android/app/build.gradle`?
`        applicationId 'se.staylive.App' 
`
The line above will always be with a capital A since the app's bundle is named exactly that.

I can see that expo prebuild adds the manifestPlaceholders above the applicationId as it should so that's working.

**Comment by poovamraj** [comment] 2023-04-05 17:20
@ttlenell changes to app.config.js are not applied until you do `expo prebuild` again. As the changes are required in the native files, that is why the changes you are doing are not reflected in your app.

**Comment by ttlenell** [comment] 2023-04-05 19:02
@poovamraj I'm very aware of that, I run `expo prebuild` before every change I make that will affect native code and also `expo prebuild --clean` a lot of the times as well.

The image below is want I meant, the `applicationId` is what I think is causing the issue since it differs if the auth0 library wants a lowercase "App". And as I said above, I've tried both lowercase and "App" in my custom schemes.
 But that is the one thing I can't change, since then the app wont get accepted on the Google play console when I update the app, since it is registered to `se.staylive.Dobb` and not `se.staylive.dobb`. 

`android/app/buld.grade`:
![image](https://user-images.githubusercontent.com/55179117/230178582-ef6c143b-ed7d-4d05-9e03-5d8e0d10a4a8.png)

Any more ideas of what I could try to make this work?
I'm very thankful for you taking the time to look into my issue

**Comment by KMathisGit** [comment] 2023-04-07 15:14
I too have this issue, I have posted some of my details and thoughts in another thread here: https://github.com/auth0/react-native-auth0/issues/582#issuecomment-1500364944

**Comment by ttlenell** [comment] 2023-04-11 12:15
> I understand that application ID cannot be changed. That is the reason we provide `customScheme`. Can you swap the customScheme to "auth0" and test it just to ensure we are getting things right.
> 
> The callback URL should be
> 
> ```
> auth0://auth.staylive.io/ios/se.staylive.App/callback, 
> auth0://auth.staylive.io/android/se.staylive.App/callback, 
> ```
> 
> The code should be
> 
> ```
>  data = await auth0.webAuth.authorize(
>         {
>           scope: 'openid profile email offline_access',
>           organization: organizationId,
>           audience: Constants.AUTH0_AUDIENCE,
>         },
>         { ephemeralSession: true, customScheme: 'auth0' },
>       );
> ```
> 
> The app.config.json should be
> 
> ```
> plugins: [
>  .....
>     [
>       'react-native-auth0',
>       {
>         domain: 'staylive.eu.auth0.com',
>         customScheme: 'auth0',
>       },
>     ],
>     ]
> ```

Hi @poovamraj and thanks again.

Sorry to say that this didn't change anything, the same issue still persists. I believe that @KMathisGit posted some interesting thoughts in the link above which might be worth looking into

**Comment by poovamraj** [comment] 2023-04-11 16:07
@ttlenell can you provide a repo that reproduces this using our sample repo?

**Comment by camchis** [comment] 2023-06-02 18:54
Anyone have a fix for this? We are using `customScheme` which only has one intent registered. Not expo project and the `customScheme` does not clash with the applicationId. We are passing in the `customScheme` in the `authorize` call too.

**Comment by ImadMachi** [comment] 2023-07-26 22:51
Thank you, I had the same problem, and I solved it by changing the package name.
for me it was because I included a digit in my package name, so I changed it from:
com.username.expoauth0 ===> com.username.expoauth

**Comment by anuragkaushik10** [comment] 2025-01-21 08:46
Recently updated react-native-auth0 to version 4.0.0 from 2.17.1 and react-native from 0.71.2 to 0.74.

Now when I am trying to login to application using universal login, it is able to get login success log at auth0 logs. But in reality the login is not redirecting back to app.

Help is highly appreciated as it is blocking us for production deployment.

If you need any additional info please let me know.


Can you reopen the issue ?

**Comment by anuragkaushik10** [comment] 2025-01-21 09:37
Its done thanks to https://github.com/auth0/react-native-auth0/issues/747#issuecomment-2439196254
