### ISSUE TITLE
Blank screen on Android

### ISSUE THREAD

**Issue by jalmonacidOA** [auth0/react-native-auth0#449] opened 2022-01-20 18:12 UTC
### Describe the problem
After login on the web browser nothing happens, the browser don't redirect to the app. On iOS works great!

### What was the expected behavior?

Been redirected to the app after login through the browser

### Reproduction

Through a custom hook we manage the bucle to force the user to log in

```
import { useEffect } from 'react';

import { useAppDispatch, useAppSelector } from '../../redux/hooks';
import { handleAuth, handleAgentAuth } from '../../redux/thunks';

export const useHandleAuth0 = () => {
  const dispatch = useAppDispatch();
  const currentState = useAppSelector((state) => state.auth);

  useEffect(() => {
    const handleAuth0 = async () => {
      const response = (await dispatch(handleAuth())) as Auth0Response;

      if (response) {
        await dispatch(handleAgentAuth(response.email, response.accessToken));
      }
    };

    if (!currentState.handleAuthResponse.accessToken.length) {
      setTimeout(() => void handleAuth0(), 1000);
    }
  }, [dispatch, currentState]);
};
```

AndroidManifest

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="XXXXXXXXXX">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/BootTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
    </application>
</manifest>
```
```
    defaultConfig {
        applicationId "xxxxxxxxxxx"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        resValue "string", "build_config_package", "xxxxxxxxxxxx"
        versionCode verCode as Integer
        versionName verName
        manifestPlaceholders = [auth0Domain: project.env.get("AUTH0_DOMAIN"), auth0Scheme: "${applicationId}"]
    }
```
```
  buildTypes {
       debug {
           applicationIdSuffix = '.dev'
           signingConfig signingConfigs.debug
       }
       dev {
           initWith release
           applicationIdSuffix = '.dev'
           matchingFallbacks = ['release']
           signingConfig signingConfigs.xxxxxxx
       }
       tst {
           initWith release
           applicationIdSuffix = '.tst'
           matchingFallbacks = ['release']
           signingConfig signingConfigs.xxxxxxx
       }
       uat {
           initWith release
           applicationIdSuffix = '.uat'
           matchingFallbacks = ['release']
           signingConfig signingConfigs.xxxxxxx
       }
       release {
           signingConfig signingConfigs.xxxxxxx
           minifyEnabled enableProguardInReleaseBuilds
           proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
       }
}
```

### Environment

- **Version of this library used:** 2.11.0
- **Which framework are you using, if applicable:** RN 0.66.4
- **Other modules/plugins/libraries that might be involved:** React-Native-Config 1.4.5

**Comment by Mr-Fraser** [comment] 2022-01-20 20:20
We have been facing similar issue for over a year now with no solution..

**Comment by pupimarti** [comment] 2022-01-20 20:28
you are using react-navigation??

**Comment by jalmonacidOA** [comment] 2022-01-21 09:58
@pupimarti yes!

**Comment by poovamraj** [comment] 2022-01-24 14:46
@pupimarti Can you provide more information on this? We are looking into this issue and it would be helpful to have more information. And if the issue is because of react-navigation we can try to provide a fix for it.

**Comment by pupimarti** [comment] 2022-01-24 16:28
https://github.com/auth0/react-native-auth0/issues/83
this is exactly same issue.
I was able to fix it by changing this



    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
        
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                Callback cb = A0Auth0Module.this.callback;

                if (cb == null) {
                    return;
                }

                boolean hasResult = resultCode == RESULT_OK &&
                        requestCode == AuthenticationActivity.AUTHENTICATION_REQUEST &&
                        data.getData() != null;
                if (hasResult) {
                    cb.invoke(null, data.getData().toString());
                } else {
                    final WritableMap error = Arguments.createMap();
                    error.putString("error", "a0.session.user_cancelled");
                    error.putString("error_description", "User cancelled the Auth");
                    cb.invoke(error);
                }

                A0Auth0Module.this.callback = null;
            }
        }, 500);
    }

**Comment by pupimarti** [comment] 2022-01-24 17:41
With this fix only works if the account is cached 😕

**Comment by poovamraj** [comment] 2022-01-26 10:27
@pupimarti @jalmonacidOA Can you confirm whether you are using `react-navigation` or `react-native-navigation`. Currently, we need a few changes to be made for React Native Navigation. React Navigation should work out of the box.

**Comment by pupimarti** [comment] 2022-01-26 11:55
@poovamraj i use react-navigation and i have the same problem with this library. The callbacks urls not works in android, the page stays in an infinite loading or in blank screen

**Comment by poovamraj** [comment] 2022-01-26 13:35
@pupimarti I integrated React Navigation into our [sample app](https://github.com/auth0-samples/auth0-react-native-sample) and followed the integration steps from the [React Navigation document](https://reactnavigation.org/docs/getting-started/) and it seems to work correctly. I would suggest creating a simple sample app that reproduces this issue so that we can figure it out further.

**Comment by jalmonacidOA** [comment] 2022-01-26 14:57
@poovamraj Yeah, mee too, im currently using react-navigation, will create a fresh react native installation and test again with auth0 and react-navigation

**Comment by jalmonacidOA** [comment] 2022-01-27 18:28
leave this test [repo](https://github.com/jalmonacidOA/auth0-react-navigation)  with auth0 and react-navigation, seems to work great, but in the project that i refer on this issue the problem persist.

**Comment by jalmonacidOA** [comment] 2022-01-27 18:34
> @poovamraj #83 this is exactly same issue. I was able to fix it by changing this
> 
> ```
> public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
>     
>     new Handler().postDelayed(new Runnable() {
>         @Override
>         public void run() {
>             Callback cb = A0Auth0Module.this.callback;
> 
>             if (cb == null) {
>                 return;
>             }
> 
>             boolean hasResult = resultCode == RESULT_OK &&
>                     requestCode == AuthenticationActivity.AUTHENTICATION_REQUEST &&
>                     data.getData() != null;
>             if (hasResult) {
>                 cb.invoke(null, data.getData().toString());
>             } else {
>                 final WritableMap error = Arguments.createMap();
>                 error.putString("error", "a0.session.user_cancelled");
>                 error.putString("error_description", "User cancelled the Auth");
>                 cb.invoke(error);
>             }
> 
>             A0Auth0Module.this.callback = null;
>         }
>     }, 500);
> }
> ```

In what file should be this code?

**Comment by poovamraj** [comment] 2022-01-28 09:25
@jalmonacidOA since the repository you provided seem to work without any issue. Can you try to figure out the differences between your project and the repository you shared? It is difficult to work on this issue without a reliable way to reproduce it.

**Comment by jalmonacidOA** [comment] 2022-01-28 13:12
@poovamraj ok, let me try to create a branch with the exact same conditions of the actual project that i've been facing the problems

**Comment by jalmonacidOA** [comment] 2022-02-02 13:07
@poovamraj Created this replica of the project that im actually working on https://github.com/jalmonacidOA/auth0-react-navigation/tree/demo-replica, seems to work on Android so basically i need to figure out through the code what's going on

**Comment by poovamraj** [comment] 2022-02-02 15:26
@jalmonacidOA I am sorry but can you clarify whether the issue is reproducing or whether the SDK works as intended?

**Comment by jalmonacidOA** [comment] 2022-02-02 18:08
@poovamraj The SDK works great on the provided repo, but even if i try to use the exact same dependencies on the original project, keeps failing.

**Comment by poovamraj** [comment] 2022-02-02 18:23
😅 That is really tricky @jalmonacidOA! We will close this ticket for now since we couldn't see a way to proceed much further. But please feel free to reopen it in case you need any assistance or if you are able to reproduce this issue.

**Closed by poovamraj** 2022-02-02 18:23 UTC
Labels: needs investigation

**Comment by jalmonacidOA** [comment] 2022-02-03 18:11
@poovamraj figure out the problem, in `andoird/app/build.gradle`, there is several buildTypes defined (the ones showed when this issue was open). The applicationIdSuffix is the problem, in the Allowed callbacks urls configuration the aplicationID is with and without the suffix, if i remove the applicationIdSuffix from the debug buildType, works perfect. So my problem is that, with the aplicationIdSuffix and a proper allowed callback, after login the app goes to a blank screen

**Comment by pupimarti** [comment] 2022-02-03 18:42
@poovamraj what would be the solution? I do not understand

**Comment by jalmonacidOA** [comment] 2022-02-04 13:24
@pupimarti add manifestPlaceholders to every environment on the buildTypes, like this:
```
    buildTypes {
        debug {
            applicationIdSuffix = '.dev'
            signingConfig signingConfigs.debug
            manifestPlaceholders = [auth0Domain: "AUTH0_DOMAIN", auth0Scheme: "APPLICATION_ID + SUFFIX"]
        }
        dev {
            initWith release
            applicationIdSuffix = '.dev'
            matchingFallbacks = ['release']
            signingConfig signingConfigs.XXXXXXX
            manifestPlaceholders = [auth0Domain: "AUTH0_DOMAIN", auth0Scheme: "APPLICATION_ID + SUFFIX"]
        }
        tst {
            initWith release
            applicationIdSuffix = '.tst'
            matchingFallbacks = ['release']
            signingConfig signingConfigs.XXXXXX
            manifestPlaceholders = [auth0Domain: "AUTH0_DOMAIN", auth0Scheme: "APPLICATION_ID + SUFFIX"]
        }
    }
```

**Comment by poovamraj** [comment] 2022-02-04 13:29
@pupimarti Do you use application suffix as well?

**Comment by ghivert** [comment] 2022-02-10 15:50
For all of you who have the same problem with buildTypes, you can do a thing a little bit more generic:

```
android {
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            applicationIdSuffix ".dev"
            if (nativeArchitectures) {
                ndk {
                    abiFilters nativeArchitectures.split(',')
                }
            }
            manifestPlaceholders = [
                auth0Domain: "AUTH0_DOMAIN",
                auth0Scheme: "${defaultConfig.applicationId}${applicationIdSuffix}"
            ]
        }
    }
}
```
You can just copy/paste the same lines `manifestPlaceholders` in each buildType.
