### ISSUE TITLE
Getting "User cancelled auth" errors for first login sometimes (android only, landscape)

### ISSUE THREAD

**Issue by gravitypersists** [auth0/react-native-auth0#529] opened 2022-10-12 16:08 UTC
edit: To anybody viewing this issue, the conversation is long, the quick answer is that this appears to be a configuration bug within the auth0 android package that this package relies on and can be fixed by incorporating this diff within `node_modules/react-native-auth0/android/src/main/AndroidManifest.xml` (use the patch-package tool for now if you need)

```diff
         <activity
             android:name="com.auth0.react.AuthenticationActivity"
+            android:configChanges="screenSize|smallestScreenSize|screenLayout|orientation|keyboard|keyboardHidden"
             android:exported="false"
             android:launchMode="singleTask"
             android:theme="@android:style/Theme.Translucent.NoTitleBar" />
```

---

We've spent a rather long amount of time digging into this problem and here's the information we've collected.

- The issue appears to only happen for one of our engineers in Ukraine (simulator) and in our testing service, lambdatest (real devices). 
  - I (from US) have connected to the same VPN as the engineer in Ukraine and cannot reproduce
  - I have not been able to reproduce his error with his credentials on my machines
  - He has reproduced his errors with my credentials on his machines (this is not a per user issue)
  - I have installed the same exact apk on both machines to same effect (no error for me, error for him, indicating this is not a build issue)
- For him, Android v12 API level 32 deterministically fails the first login attempt, and subsequent login attempts succeed.
  - I have tried the same device simulator and api level (this should not be an API level issue)
- Android v10 appears to be non-deterministically failing (unsure if this is the same error or a different one) unlike API 32
- The issue started at sometime between August 31 (we think, last successful test run) and September 3 with no app/lib updates on our end 
- RN v68.1 and we've tried react-native-auth0 v2.13.1, 2.13.3, and 2.14.0
- This issue does not exist on ios, both of us have no trouble logging in onto ios.

Whenever I login correctly, I can see both a "Success Login" and "Success Exchange" within our auth0 logs, like so:

![image](https://user-images.githubusercontent.com/231863/195387945-72ace0f5-789b-4d1a-ad8b-4f491383f793.png)

Whenever this issue occurs, I only see a "Success Login." Attempting to login again immediately after produces another "Success Login" but with a "Success Exchange" this time, meaning that we need to login twice in order to actually login.

The first attempt produces the [fallthrough error "User cancelled auth"](https://github.com/auth0/react-native-auth0/blob/89a7c9dc5f2ddd0d315b1249c88266cb8002ee01/android/src/main/java/com/auth0/react/A0Auth0Module.java#L239)

Final regards: I suspect this might be some type of security measure in combination with android specific implementation in this library. I can provide more information if needed.

**Comment by poovamraj** [comment] 2022-10-13 12:24
Hi @gravitypersists thanks for the detailed report. As you mentioned, I am not able to reproduce this on my end as well. 

We had a similar error reported previously but couldn't continue much due to lack of information - https://github.com/auth0/react-native-auth0/issues/504

The only place for this to fallthrough is when [this condition](https://github.com/auth0/react-native-auth0/blob/89a7c9dc5f2ddd0d315b1249c88266cb8002ee01/android/src/main/java/com/auth0/react/A0Auth0Module.java#L231) returns false.

Can you try to Log that particular place in the environment where the issue is happening to gather more information? You can fork the library and use that version or make the changes inside `node_modules`. The Log can be viewed using `adb logcat` command.

**Comment by poovamraj** [comment] 2022-10-13 18:45
I assumed the issue would be with the `data` object received but it looks like it is null

1. We can try to debug what happens when the browser opens and what URL is provided for redirection. This can be done by opening the Chrome browser and going to chrome://inspect/#devices. You can let me know what is the callback URL that is received. 

2. The redirection happens through `RedirectActivity` and `AuthenticationActivity#onResume`. Can we log in and see what the results we are getting are?

3. We can try to run the Android SDK to see if a similar error happens in it as well or whether it happens only in React Native. We can easily test this. You can pull our [Android repository](https://github.com/auth0/auth0.android) and run the sample application which is already configured and ready to run. You can try Web Auth in it which should follow the same mechanism.

It would be interesting to know whether the issue occurs also for Android SDK in the same environment

Sorry that there are so many cases to check but since it is not reproducible here I wanted to cover all ground to see whats happening.

**Comment by poovamraj** [comment] 2022-10-14 14:36
Also, can you verify whether `AuthenticationActivity#onNewIntent` is called? It is critical to set the information received from callback URL here

**Comment by poovamraj** [comment] 2022-10-14 17:46
I guess we figured the issue right there. It is one of the old suspects we faced in the Android app. Basically `onResume` is called before `onNewIntent` which is causing the flow to be disrupted.

In an application where the issue doesn't reproduce the logs will execute in this order
```
D/XO-onCreate intent: com.auth0samples://poovamraj.eu.auth0.com/android/com.auth0samples/callback?code=xxx
D/XO-onNewIntent: com.auth0samples://poovamraj.eu.auth0.com/android/com.auth0samples/callback?code=xxx
D/XO-onResume resultMissing: com.auth0samples://poovamraj.eu.auth0.com/android/com.auth0samples/callback?code=xxx
```

1. Do you have the application in landscape mode?
2. What is the target version of the Android app?
3. Can you try adding this [line](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/AndroidManifest.xml#L12) of code under [here](https://github.com/auth0/react-native-auth0/blob/master/android/src/main/AndroidManifest.xml#L10) and see if it fixes it?

**Comment by gravitypersists** [comment] 2022-10-14 20:40
1. Yes, we enforce landscape for now
2. compileSdkVersion = 31, targetSdkVersion = 30
3. Yes, this fix actually unstuck our engineer in Ukraine, but now in our automated QA test environment we are seeing this 
![image (2)](https://user-images.githubusercontent.com/231863/195938676-14670bc5-1a7b-44c8-b309-6e484e68698e.png)

(I need to check to see if that was happening before we ever experienced this error, but it looks like we've found a solution! Thank you so much Poovamraj! We'll use [patch-package](https://www.npmjs.com/package/patch-package) until the change is in npm.

**Comment by poovamraj** [comment] 2022-10-14 23:16
@gravitypersists you can checkout this issue for more details on that - https://github.com/auth0/react-native-auth0/issues/531

**Comment by poovamraj** [comment] 2022-10-15 22:26
Hi @gravitypersists, We have fixed this issue in this PR - https://github.com/auth0/react-native-auth0/pull/534

We will keep you informed once it is released. We will close this issue for now. Please feel free to reopen this issue if you have more doubts on this.

**Closed by poovamraj** 2022-10-15 22:26 UTC
Labels: bug

**Comment by poovamraj** [comment] 2022-10-19 11:42
And the fix is available now - https://github.com/auth0/react-native-auth0/releases/tag/v2.14.1
