### ISSUE TITLE
Signup with Apple ID throws error `invalid_client`

### ISSUE THREAD

**Issue by bhoomika911** [auth0/react-native-auth0#651] opened 2023-06-15 22:39 UTC
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi, I am trying to signup with AppleId and after  adding credentials, it throws this error:

**Code for registration:**

```
const credentials = await auth0.webAuth.authorize({
                scope: 'openid profile email offline_access',
                audience: Config.AUTH0_AUDIENCE,
                prompt: 'login',
            });
```

**Error:**
```
{
...
"connection": "apple",
"error": {
"message": "invalid_client",
"oauthError": "invalid_request",
"type": "request-error"
},
...
}
```

Can anyone please help? I am not sure what's going wrong in request which cause this error.

Thank you!

### Reproduction

Step 1: Try to sign up with apple id.
Step 2: Added email and password
Step 3: Submitting password close oauth webview screen and show this error(Error: `invalid_client `) in logs.

### react-native-auth0 version

2.10.0

### React Native version

"0.66.2

### Expo version

NA

### Platform

Android, iOS

### Platform version(s)

All devices

**Comment by poovamraj** [comment] 2023-06-25 08:38
Hi @bhoomika911 

The invalid_client error is thrown if Apple was unable to authenticate the client (your application registered with Apple). Have you confirmed the Services ID (Client ID), Apple Team ID, Client Secret Signing Key, and Key ID in the Apple developer console? 

docs: [https://auth0.com/docs/connections/apple-siwa/set-up-apple](https://auth0.com/docs/connections/apple-siwa/set-up-apple)
[https://auth0.com/docs/connections/apple-siwa/troubleshooting#types-of-errors](https://auth0.com/docs/connections/apple-siwa/troubleshooting#types-of-errors)

Since this isn't a bug on the SDK end. We will close this issue. Please feel free to comment here if you have more doubts and we can reopen this.

**Closed by poovamraj** 2023-06-25 08:38 UTC
Labels: bug
