### ISSUE TITLE
Auth0 cancelling authentication flow during webAuth.authorize() call

### ISSUE THREAD

**Issue by erumas** [auth0/react-native-auth0#600] opened 2023-03-01 13:53 UTC
### Description

When calling```auth0.webAuth.authorize()``` the authentication throws an error that states: ```{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}``` This breaks the login flow and does not allow the user to continue. 

When we check the logs in our Auth0 dashboard we see that the user successfully logged in. It seems this is an error in the auth0 react-native client. We suspect that the callback is not resolving properly but are unable to debug the issue further. 

This started occurring when we upgraded our Gradle version 7.1.1 and react-native 0.69.8 and bumped react-native-auth0 to 2.17.1

### Expected behavior:

After the call to ```webAuth.authorize()``` the user is redirected to a web-auth login page where they can enter their credentials, after which the callback resolves returning an accessToken

--or--

if they have already logged in, and credentials are cached we should expect the callback to resolve so that we can use the accessToken and allow the user to login. 

### Reproduction
This is a consistent failure for each login attempt

Step 1:
```
const App: React.FC () => {
  <Auth0Provider
      domain={'some.client.domain.com'}
      clientId={'some_secret_client_id'}
    >
      ....
      <App />
  </Auth0Provider>
}
```

```react-native run-android``` 

Step 2:
after app builds attempt to authenticate within the <App />:
```
const auth0Instance = await getAuth0Instance();
const connectionConfig = { 
  scope: 'openid profile email offline_access',
  audience: 'some.client.instance.com'
 }
const { accessToken, refreshToken, expiresIn } =
        await auth0Instance.webAuth.authorize(connectionConfig);
```

Step3:
should be the async function resolving but instead an error is thrown:
```  {"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}```

### Environment

```
        buildToolsVersion = "31.0.0"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
        supportLibVersion = "31.0.0"
        kotlin_version = "1.6.0"
```
react-native-auth0: 2.17.1
react-native: 0.69.8

### Update
We created a fresh repository to try and narrow down the issue. It seems to occur independently of the change to the react-native version. It seems to occur precisely when we upgrade from Node 16.x to Node 18.0.0

### More specifics
The async action fails specifically here:

``` react-native-auth0/android/src/main/java/com/auth0/react/A0Auth0Module.java ```

    @Override
    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
        Callback cb = A0Auth0Module.this.callback;

        if(requestCode == LOCAL_AUTH_REQUEST_CODE) {
            secureCredentialsManager.checkAuthenticationResult(requestCode, resultCode);
            return;
        }

        if (cb == null) {
            return;
        }

        boolean hasResult = resultCode == RESULT_OK &&
                requestCode == AuthenticationActivity.AUTHENTICATION_REQUEST &&
                data.getData() != null;
        if (hasResult) {
            cb.invoke(null, data.getData().toString());
        } else {
            final WritableMap error = Arguments.createMap();
            error.putString("error", "a0.session.user_cancelled");
            error.putString("error_description", "User cancelled the Auth");
            cb.invoke(error);
        }

        A0Auth0Module.this.callback = null;
    }

When we log the ```data``` it's present but for some result the ```resultCode``` fails this check, and the error above is throw in the else branch when the ```cb.invoke(error);``` is called

**Comment by lhuber92** [comment] 2023-03-07 10:29
The error you're getting may be related to using a custom scheme and not specifying it in the call, at least it was for me since I had to add one in order to avoid duplicate "login with" popup when calling the login. It seems rather generic and seems to happen for many types of errors.

Note that I'm using Expo.

Try this:

```
    const tokenResult = await auth0.webAuth.authorize( { scope: 'openid profile email offline_access', audience: Constants.expoConfig.extra.YOUR_CUSTOM_SCHEME }, {
      customScheme: Constants.expoConfig.extra.AUTH_SCHEME
    } )
```

And in app.config.js

```
module.exports = {
  expo: {
    scheme: "somescheme",
    extra: {
      AUTH_SCHEME: "someotherscheme"
    },
    plugins: [
      [
        "react-native-auth0",
        {
          domain: "your domain",
          customScheme: "someotherscheme",
        }
      ]
    ],
  }
}
```

Note that I use two different schemes to avoid the duplicate app popup. Also, the schemename has to be in lowercase.

Finally, add your callbacks in allowed callback urls and allowed logout urls:

someotherscheme://xxx/ios/xxx/callback, 
someotherscheme://xxx/android/xxx/callback,

Hope that helps

**Comment by ajstokar** [comment] 2023-03-11 14:17
I'm having this exact same problem in android emulator (Pixel 6 Pro API 31)

Calling this
```
auth0.webAuth.authorize({
            scope: 'openid profile name email offline_access',
            prompt: 'login',
        })
```
        
After successful authentication (confirmed in the auth0 console), I get back this response:
`{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}`


Environment
buildToolsVersion = "33.0.0"
minSdkVersion = 28
compileSdkVersion = 33
targetSdkVersion = 33
kotlin_version = "1.8.0"
react-native-auth0: 2.17.1
react-native: 0.70.7

**Comment by poovamraj** [comment] 2023-03-13 08:17
@erumas, does @ajstokar's fix work for you? Are you seeing this in the sample as well.

Can you share the fresh repository you mentioned through Github (without any sensitive info) so that we can use it to reproduce this.

Also you mention the issue about node version, does the same project work in Node 18 with same device and doesn't work in Node 16?

**Comment by erumas** [comment] 2023-03-15 10:26
@poovamraj I'm not sure I see a fix with @ajstokar's comment. We use react-native-navigation but it's integral to our application, it's not possible for us to remove it.

**Comment by ajstokar** [comment] 2023-03-15 12:41
It seems to be working for me now with the following changes:

AndroidManifest.xml
```
<intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="com.example" />
              <data android:scheme="my-data" />
          </intent-filter>
```


MainActivity.java
```
protected void onCreate(Bundle savedInstanceState) {
      SplashScreen.show(this);
      super.onCreate(savedInstanceState);
  }
```

Previously, I was passing null to super.onCreate which I believe caused the issue, but I'm not 100% sure.

**Comment by ajstokar** [comment] 2023-03-16 17:31
Ok, now it's happening to me again...we have a 'dev' and 'stage' environment.  Dev is working, stage is not, with the exact same code.  I wondering if it could be the auth config?  Very frustrating.

**Comment by poovamraj** [comment] 2023-03-17 14:38
@erumas @ajstokar the problem seems to be stemming from the use of react-native-navigation. You can check out this thread that discusses why this SDK is currently not able to support along side RNN - https://github.com/auth0/react-native-auth0/issues/83. Any feedback or workaround is more than welcome.

**Comment by poovamraj** [comment] 2023-04-04 09:53
@erumas any update on the issue here?

**Comment by poovamraj** [comment] 2023-04-06 11:05
@erumas closing this issue because of no update. Feel free to comment here and we can reopen this issue for you.

**Closed by poovamraj** 2023-04-06 11:05 UTC
Labels: waiting for customer

**Comment by Flotemer** [comment] 2023-07-25 22:25
Wondering if any fix was ever found for this. We currently use react navigation as well and this is game breaking on our android version.

**Comment by poovamraj** [comment] 2023-07-25 22:57
@Flotemer did you try our latest beta version of the SDK? If so can you provide us with a reproduceable sample using our sample project and we will definitely look into it.

**Comment by Flotemer** [comment] 2023-07-27 19:31
@poovamraj   , I have not, thought we were using the latest, but turns out we aren't. Will try with the beta and circle back.

**Comment by Flotemer** [comment] 2023-09-18 20:18
@poovamraj, upgraded to 3.0. IOS migration worked fine, but now unable to get the callback to work on android at all after removing the intent filters. 

Whats the best way to share an example with you that reproduces the issue?
