### ISSUE TITLE
Dismissing the auth modal on iOS by dragging causes app to hang

### ISSUE THREAD

**Issue by alexbrazier** [auth0/react-native-auth0#331] opened 2020-08-20 16:09 UTC
### Description

On iOS 13 and above the authentication window opens a modal when calling `webAuth.authorize` - see image below:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/5689874/90795296-c785d580-e305-11ea-8ad5-76835891372b.png">

It's possible to drag the window from the top to dismiss it. When the user does this we get stuck "awaiting" the `authorize` command to finish, but it never does.

If the user clicks the "cancel" button we get an error saying "user_cancelled" as expected. I would expect the same error to be thrown after the user dismisses the modal as described above.

### Reproduction

Code sample:

```typescript
const client = new Auth0({ domain, clientId });

try {
  const result = await authClient.webAuth.authorize(
    {
      scope: 'openid',
    },
    {
      ephemeralSession: true,
    },
  );
} catch (err) {
  console.log(err) // user_cancelled
}
```

Run on iOS 13 or above and then drag down the modal to dismiss it.

#### Expected
"user_cancelled" error to be thrown

#### Actual
Nothing happens, no error is thrown and you get stuck waiting for `authorize`

> NOTE: I only seem to be able to dismiss the modal by dragging on a physical device (tested on iPhone 8)

### Environment

- **Version of this library used:** 2.5.0
- **Other relevant versions (language, server software, OS, browser):** iOS `13.6` iPhone 8 Physical device

**Comment by Widcket** [comment] 2020-08-26 17:40
Hi @alexbrazier I was not able to reproduce it with the [sample app](https://github.com/auth0-samples/auth0-react-native-sample) (on an iPhone 11 Pro):

![RPReplay_Final1598463274](https://user-images.githubusercontent.com/5055789/91337573-f2f73d00-e7a9-11ea-8f47-fa8d78b8fb3e.gif)

Can you please record a video showing the issue?

**Comment by alexbrazier** [comment] 2020-08-27 11:28
Thanks for looking into it @Widcket, I've just tested the sample app on my iPhone 8 and it seems to be working as expected there. I'll see if I can work out what the other differences are, or if it is fixed in the latest version.

**Comment by alexbrazier** [comment] 2020-08-27 12:01
I've worked out it's an issue with `ephemeralSession: true`, I tried updating to the latest version and that didn't fix the issue either.

I've created a branch with the changes required to cause this error https://github.com/auth0-samples/auth0-react-native-sample/compare/master...alexbrazier:login-error-demo

See the recording below:

![RPReplay-Final1598528508](https://user-images.githubusercontent.com/5689874/91438589-83458880-e863-11ea-9404-d832745c471b.gif)

> Cancel button works as expected and triggers the `.then` but dragging does not.

**Comment by Widcket** [comment] 2020-08-28 20:17
@alexbrazier indeed that only happens with `ephemeralSession: true`. I've been able to reproduce it on a barebones Swift app without the SDK, using only `ASWebAuthenticationSession`:

```swift
import UIKit
import AuthenticationServices

class ViewController: UIViewController {
    var webAuthSession: ASWebAuthenticationSession?

    let authURL = URL(string: "https://{YOUR_AUTH0_DOMAIN}/authorize?nonce=1234&client_id={YOUR_AUTH0_CLIENT_ID}&response_type=id_token&connection=google-oauth2&prompt=login&scope=openid%20profile&redirect_uri={YOUR_CALLBACK_URL}")!
    let callbackUrlScheme = "{YOUR_CALLBACK_URL}"

    @IBAction func login() {
        self.webAuthSession = ASWebAuthenticationSession(url: authURL,
                                                         callbackURLScheme: callbackUrlScheme,
                                                         completionHandler: { (callBack: URL?, error: Error?) in
            guard error == nil, let successURL = callBack else {
                return print("Error: \(String(describing: error))")
            }

            print("Success: \(successURL.absoluteString)")
        })
        
        self.webAuthSession?.prefersEphemeralWebBrowserSession = true // Using false it doesn't happen
        self.webAuthSession?.presentationContextProvider = self
        self.webAuthSession?.start()
    }
}

extension ViewController: ASWebAuthenticationPresentationContextProviding {
    func presentationAnchor(for session: ASWebAuthenticationSession) -> ASPresentationAnchor {
        return UIApplication.shared.windows.first!
    }
}
```

So it looks like a bug on Apple's side. We'll file a bug report with them, and advise you to do the same. The more people report it, the better.

**Comment by Widcket** [comment] 2020-09-01 14:29
We'll keep this issue open and pinned for future reference.

**Comment by Widcket** [comment] 2020-09-17 02:26
@alexbrazier this is now fixed on iOS 14.

**Closed by Widcket** 2020-09-17 02:26 UTC
