### ISSUE TITLE
Android: Switching apps to get the SMS code dismisses the Auth0 modal

### ISSUE THREAD

**Issue by fbartho** [auth0/react-native-auth0#459] opened 2022-02-18 18:20 UTC
### Describe the problem

On our Android devices, when you app-switch to get the Auth-code from your Messaging application, when you return to our App, the Auth0 modal dismisses, so you're forced to restart the process, and hopefully see the Auth-code from the notification-overlay.

This is a duplicate of #438, but I can't reopen that ticket.

I've verified that the Auth0 tenant is marked as `Production`, and this was initially discovered via customer service complaints.

### What was the expected behavior?

App-switching should leave the Auth0 login modal webview visible.
On iOS this does not occur.

### Reproduction

I don't have a small reproduction sample, but #438 does. I have a video recording, but it includes a private phone number, and I don't yet know how to mask that out. Please advise if you'd like me to research that.

1. Launch the app (on Android)
1. Click the Login button
1. Fill in your phone number for SMS passwordless auth
1. Switch to your Messaging app to read the code
1. Switch back to the app, and find that the web view has dismissed itself, and you have to start over

### Environment

- **Version of this library used:** `2.3.8`
- **Which framework are you using, if applicable:** N/A
- **Other modules/plugins/libraries that might be involved:** N/A
- **Any other relevant information you think would be useful:** N/A

**Comment by fbartho** [comment] 2022-02-18 19:02
There are `useMemo` and `useCallback` that are wrapping the relevant chunks of code for our API & AuthProvider component.

At a higher-level than the Auth components, there is a component that listens for background/foreground changes to send analytics events. 

>Also can you let us know how you are ensuring the app is marked in production when you were reproducing?

I logged in to auth0, and looked at the label under the Tenant drop-down. Additionally, we use `.env` files to configure our app for Dev/Staging/Production and it's definitely connecting to the right tenant, and other fields from the `.env.production` are properly reflected in the app.

**Comment by fbartho** [comment] 2022-02-18 19:25
>1. Will it be possible to provide a sample app?

Sorry, I'm not able to do this right now, as I'm just representing the team operating on other timezones.

>2. I understand that the app is in prod configuration. But it can still be connected to a debugging server if you run the app using commands like yarn run android.

Sorry I was unclear -- we're reproducing this in our Production app downloaded from the Play Store, so it's definitely not connected to a debug server. Customers in the wild are also reporting this.

>3. Can you try opening the app without clicking the icon and instead of opening it from the task manager after going out and see if the issue reproduces?

If you use the Task Manager instead of clicking the App Icon, then the problem does not occur. -- What does this imply?

**Comment by poovamraj** [comment] 2022-02-18 19:31
> If you use the Task Manager instead of clicking the App Icon, then the problem does not occur. -- What does this imply?

This means intent is sent invoking a new activity instance instead of just reusing the already running activity. We noticed this behaviour when connected to debugging server but not while running the application without it.

Thanks for reporting this issue. We will look into this.

**Comment by mostafa-abardeh** [comment] 2022-05-04 00:43
We are experiencing this exact issue. @poovamraj  any updates ?

**Comment by poovamraj** [comment] 2022-06-08 07:10
@mostafa-abardeh we are not able to reproduce this issue on our end, will it be possible to provide the reproduction steps so that we can work on this?

**Comment by poovamraj** [comment] 2022-08-20 13:41
@fbartho @mostafa-abardeh, we are closing this issue for now since we are not able to reproduce this in a production version. Please feel free to reopen this with a sample application & repo. It will be of great help. Thanks

**Closed by poovamraj** 2022-08-20 13:41 UTC
Labels: bug
