### ISSUE TITLE
Getting issue on Android and iOS App with Facebook login

### ISSUE THREAD

**Issue by SudhanshuAgrahary** [auth0/react-native-auth0#549] opened 2022-11-08 05:27 UTC
I’ve integrated Facebook login using reat-native-auth0. Both iOS and Android App is on production already, suddenly Facebook login is not working with both iOS and Android. when we debug the Android App and found the following issue “{“error”: “a0.session.user_cancelled”, “error_description”: “User cancelled the Auth”}” when calling auth0.webAuth.authorize API. I checked callback URL, tenant and domain all thing is correct. Any inputs this regard will be helpful.

Version of this library used: "react-native-auth0": "^2.6.0"
Which framework are you using, if applicable: "react-native": "0.63.3",

**Comment by poovamraj** [comment] 2022-11-10 14:08
Hi @SudhanshuAgrahary, I tried this out in Android and couldn't reproduce this. I used our [Sample Application](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks) and I am adding a recording here. Can you please try to reproduce this in our sample application so that we will have a reproducible environment to work with?


https://user-images.githubusercontent.com/15910425/201113212-7ab344a5-5b7d-4eb8-9c44-e4c87c2e6dc6.mov

**Comment by poovamraj** [comment] 2022-11-14 10:16
Hi @SudhanshuAgrahary, we will close this issue for now. Please feel free to reopen it with more information.

**Closed by poovamraj** 2022-11-14 10:16 UTC
Labels: waiting for customer
