### ISSUE TITLE
Anyway we can hide browser which open while  auth0.webAuth.clearSession session

### ISSUE THREAD

**Issue by jariwalabhavesh** [auth0/react-native-auth0#253] opened 2019-11-06 09:57 UTC
### Describe the problem you'd like to have solved

> Right now whenever you call the  auth0.webAuth.clearSession function in the app then the browser will be open for couple of seconds and close back(In ios only).

### Describe the ideal solution

> Any way we can avoid opening a browser while clearSession because while logout it looks weird that browser opens up and doesn't show something and close. I think it feels like a bad user experience. In android, it is not opening any browser while calling .clearSession method. Only opening in ios

**Comment by winseyli** [comment] 2019-12-04 04:29
+1

**Comment by stigi** [comment] 2019-12-20 13:24
For us the workaround was to just never clear the session, but to just clear your tokens and start new sessions with the `prompt=login` option. In our case we just wanted to clear the session so the user got the chance to start login from scratch.

**Comment by lbalmaceda** [comment] 2020-01-09 19:44
That's following Apple guidelines, and prompt would depend on the iOS version. 
Closing as dupe of https://github.com/auth0/react-native-auth0/issues/226.

**Closed by lbalmaceda** 2020-01-09 19:44 UTC
