### ISSUE TITLE
Manifest merge fails when building androidTest package due to missing placeholder substitution

### ISSUE THREAD

**Issue by raldred** [auth0/react-native-auth0#387] opened 2021-07-01 12:39 UTC
### Describe the problem

We use detox/espresso to test our application. It builds a second application `androidTest` which is used alongside the main application to run grey box e2e tests.

Gradle fails processing the manifest for the test application. manifestPlaceholders substitutions are required.
The main application builds fine.

We're not using the webAuth so have both the manifestPlaceholders defined and the snippet to remove the activities in AndroidManifest

We've gone back to 2.8.3 for now.

### Reproduction
1.
Using the detox react native android example:
https://github.com/wix/Detox/tree/master/examples/demo-react-native

2.
Add auth0 as a dependency to the main project as per readme

3.
Configure the `manifestPlaceholders` in app/build.gradle

4.
As we're not using the webAuth parts of this lib, also add the remove snippets to the AndroidManifest
```
      <activity
        android:name="com.auth0.react.AuthenticationActivity"
        tools:node="remove"/>
      <activity
        android:name="com.auth0.react.RedirectActivity"
        tools:node="remove"/>
```
5.
Build the main app and the test app.
`./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release`

6.
Build will fail
```
node_modules/react-native-auth0/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger7170877575298229251.xml Error:
        Attribute data@host at manifestMerger7170877575298229251.xml requires a placeholder substitution but no value for <auth0Domain> is provided.
node_modules/react-native-auth0/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger7170877575298229251.xml Error:
        Attribute data@scheme at manifestMerger7170877575298229251.xml requires a placeholder substitution but no value for <auth0Scheme> is provided.
```
### Environment

- **Version of this library used:** 2.9.0
- **Which framework are you using, if applicable:** RN 0.63.3
- **Other modules/plugins/libraries that might be involved:** Detox 17.9.0
- **Any other relevant information you think would be useful:**
I believe it's possible the manifestPlaceholders are not injected into android manifests for android test applications.

**Comment by Widcket** [comment] 2021-07-01 23:26
Hi @raldred, are you adding the manifest placeholders to the test app?

**Comment by mattryles** [comment] 2021-07-16 13:36
Hi, 
I'm facing the same issue.
When you say to the test app, do you mean the detox app? 
How would I add these to the test app? 
They are within the defaultConfig in ther build.grade.

**Comment by Widcket** [comment] 2021-07-16 14:32
Hi @mattryles, if you're using a separate app to run the tests, then that app needs to have the manifest placeholders in its own Manifest.

**Comment by mattryles** [comment] 2021-07-16 14:35
Thanks for the response. The tests are in the same app. Are the placeholders required if you’re not using the web auth stuff?

**Comment by Widcket** [comment] 2021-07-16 14:41
@mattryles no they're not. Please see https://github.com/auth0/react-native-auth0#skipping-the-web-authentication-setup

**Comment by mattryles** [comment] 2021-07-16 14:50
Cheers. I will rip them out.
Detox doesn’t support web views from my experience and I know you guys push devs down the web view route so this maybe why it’s not popped up much.
To replicate:
- Create empty react native project (crna)
- add react-native-auth0
- Add detox.
- iOS is fine, android isnt.
It’s likely how detox handles the build - but I’m not up on grade 🤷

**Comment by mattryles** [comment] 2021-07-16 15:25
Still fails on build :( 
Any more pointers?

**Comment by raldred** [comment] 2021-07-16 20:17
Yeh despite not using the web auth and adding the placeholders and the remove snippets, gradle still refuses to compile the test app.

For now we're back on 2.8.3.

**Comment by lbalmaceda** [comment] 2021-07-23 13:32
I suggest you add an `AndroidManifest.xml` file in the `test` source folder, where you either remove these activities or replace their intent-filter declaration with some hardcoded values, so they don't depend on "manifestPlaceholders".

i.e.

```xml
<activity
      android:name="com.auth0.react.RedirectActivity"
      android:exported="true">
      <intent-filter>
          <action android:name="android.intent.action.VIEW" />

          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />

          <data
              android:host="company.auth0.com"
              android:pathPrefix="/android/app.company.sample/callback"
              android:scheme="https" />
      </intent-filter>
</activity>
```

**Comment by markpar** [comment] 2021-09-03 19:53
Could I petition to reopen this issue?  I have time and resources to devote to investigating this issue, so am happy to help in any way I can.  

I tried the solution from @lbalmaceda but still hit the same error.  Here's the `AndroidManifest.xml` I placed in `android/app/src/androidTest`:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.---.---.test">
    <application>
        <activity
            android:name="com.auth0.react.RedirectActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="company.auth0.com"
                    android:pathPrefix="/android/app.company.sample/callback"
                    android:scheme="https" />
            </intent-filter>
        </activity>
    </application>
</manifest>
```
Error
```
> Task :react-native-auth0:processDebugAndroidTestManifest FAILED
/Users/mparris/dev/<redacted>/node_modules/react-native-auth0/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger11471523469033098982.xml Error:
        Attribute data@host at manifestMerger11471523469033098982.xml requires a placeholder substitution but no value for <auth0Domain> is provided.
/Users/mparris/dev/<redacted>/node_modules/react-native-auth0/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger11471523469033098982.xml Error:
        Attribute data@scheme at manifestMerger11471523469033098982.xml requires a placeholder substitution but no value for <auth0Scheme> is provided.
```
The command I'm using to build is `./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug` (per Detox instructions).

I also tried explicitly removing the activities as instructed [here](https://github.com/auth0/react-native-auth0#skipping-the-web-authentication-setup), but get the same error.

It _sounds_ like the issue is getting the manifest placeholders passed into the `.test` app.  Is that accurate?

**Comment by markpar** [comment] 2021-09-07 20:17
@lbalmaceda thanks for reopening!  I'm not using Robolectric, just Detox.  I did create an `AndroidManifest.xml` in the `app/src/androidTest` folder, with the contents from your previous comment, but it didn't work.  I also tried it in a `test` folder, with the same results.

Thanks for the link to the example test manifest.  Mine looks very similar but there are a few differences, so I'll check those out.  Thanks also for the info about the `testOptions` section of `build.gradle`; I'll check that out, too.

I did try creating build configs or product flavors for `test`/`androidTest`, but those are reserved words and Gradle doesn't allow them for config or flavor names, so that wasn't possible.

I'll let you know how I get on with the info you provided.

**Comment by lbalmaceda** [comment] 2021-09-10 10:47
@markpar I'm not familiar with Detox. I see they have a disclaimer that they [only support specific RN versions](https://github.com/wix/Detox#react-native), you might want to double-check if that's affecting you.

If with the options above your test build is not getting that manifest file replaced, then there must be something in one of those gradle steps when you run it with Detox that for some reason is not running that "prepare resources" part.

Regarding the folders, `androidTest` would affect your integration tests (i.e. espresso) and `test` would affect your unit tests (jUnit, robolectric, etc)

**Comment by markpar** [comment] 2021-09-10 17:44
Thanks for the reply, @lbalmaceda!  Unfortunately, the two suggestions you made didn't work for me.  It seems like they _should_, but neither the `testOptions` settings nor creating `android/app/src/androidTest/AndroidManifest.xml` and copying the contents of https://github.com/auth0/Auth0.Android/blob/main/auth0/src/test/AndroidManifest.xml into it worked (got the same error).  Also, we are on React Native 0.63.4, which is supported by Detox on Android.  

I can confirm @raldred's findings that simply adding `react-native-auth0` to a project with Detox installed causes the `androidTest` build to break.  The really weird thing is that an androidTest APK *is* generated, I can run tests, and get authenticated with Auth0 via `react-native-auth0`.  That is, everything works!  😕 

I tried an experiment where I added a new placeholder and then referenced it in `app/src/androidTest/AndroidManifest.xml` and the resulting merged manifest had the placeholder value, so I think the placeholder values are indeed being passed through but I'm not sure why `react-native-auth0` isn't seeing them.  I made a repo that shows the behavior at https://github.com/markpar/mptest if anyone wants to take a look.  It's a skeleton RN project.

My main problem is that I don't know the Gradle process well enough to know what _could_ be happening.  That's where I'll continue to research.  I don't know how long that will take, so if you want to close this issue in the meantime to get it off your plate, that'd be fine with me.  I could comment here with any new findings I may uncover and you can reopen it if you think it's appropriate.

**Comment by markpar** [comment] 2021-09-10 18:49
Here's the full text of the error message, if it helps:
```
> Task :react-native-auth0:processDebugAndroidTestManifest FAILED
[androidx.vectordrawable:vectordrawable-animated:1.0.0] /Users/mparris/.gradle/caches/transforms-3/8705c465ed2dda5142c337dec9efb27d/transformed/vectordrawable-animated-1.0.0/AndroidManifest.xml Warning:
        Package name 'androidx.vectordrawable' used in: androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.vectordrawable:vectordrawable:1.0.1.
/Users/mparris/dev/mptest/node_modules/react-native-auth0/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger13632322597102775531.xml Error:
        Attribute data@host at manifestMerger13632322597102775531.xml requires a placeholder substitution but no value for <auth0Domain> is provided.
/Users/mparris/dev/mptest/node_modules/react-native-auth0/android/build/intermediates/tmp/manifest/androidTest/debug/manifestMerger13632322597102775531.xml Error:
        Attribute data@scheme at manifestMerger13632322597102775531.xml requires a placeholder substitution but no value for <auth0Scheme> is provided.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```
Ignore the warning about `androidx.vectordrawable`; it's unrelated.

**Comment by lbalmaceda** [comment] 2021-09-13 14:55
@markpar Thanks for sharing that PoC project. I think it could help others if you add the list of commands that need to be run to reproduce this. i.e. Detox CLI set up, commands to run tests, expectations, and actual results, etc. 

There's not much information on using Detox along with Manifest Placeholders. This is what I could find, where it seems to enforce that the final configuration for a specific project (name hardcoded) is always defined before build time. You might want to give it a try: https://github.com/OneSignal/react-native-onesignal/issues/579#issuecomment-442504553

I'll leave this open for a while in case someone else knows the answer. Cheers

**Comment by markpar** [comment] 2021-09-13 17:39
@lbalmaceda Thank you for the suggestion on my test repo.  I'm actually a tester by trade and am a bit ashamed that I forgot to include instructions!  🤣   I've added a readme that shows the commands to reproduce the error as well as expected behavior.  I also included a quick list of how I set up the project.  

Nice find in the OneSignal repo!  I'll definitely try that out.

**Comment by markpar** [comment] 2021-09-13 18:56
Good news!  The method suggested in the OneSignal repo [here](https://github.com/OneSignal/react-native-onesignal/issues/579#issuecomment-442504553) worked!  I added this section to `android/build.gradle` and now my Detox build is successful.
```
subprojects {
    afterEvaluate { subproject ->
        if (subproject.name == 'react-native-auth0') {
            def String taskRequests = getGradle().getStartParameter().getTaskRequests().toString()
            if (taskRequests.contains("assembleAndroidTest")) {
                android {
                    defaultConfig {
                        manifestPlaceholders = [auth0Domain: "E2E_TEST", auth0Scheme: "com.E2E.TEST"]
                    }
                }
            }
        }
    }
}
```
I verified that those placeholder values are indeed being fed through to `android/app/build/intermediates/merged_manifest/debug/AndroidManifest.xml`.  When I build the regular version of the app, I get the "real" values from the `defaultConfig` section of `android/app/build.gradle`.  When I build the Detox version, the merged manifest contains the E2E test values.  👍    I've updated the [example repo](https://github.com/markpar/mptest) with this change

I don't know Gradle well enough to say if this is the "correct" solution, but it definitely works for me.  Many, many thanks for your assistance, @lbalmaceda!

**Comment by raldred** [comment] 2021-09-13 20:32
Thanks for looking into this @lbalmaceda & @markpar.
I'll add this to our maintenance window next week to try this out.

**Comment by lbalmaceda** [comment] 2021-09-14 11:45
I'm glad you were able to resolve the issue! I'll close this but if you run into more trouble let me know and I'll re-open. Cheers

**Closed by lbalmaceda** 2021-09-14 11:45 UTC
Labels: waiting for customer

**Comment by hesham2255** [comment] 2022-10-04 18:54
its not worked with google play requirement targetSdkVersion 31, please update

**Comment by AndyWatt83** [comment] 2023-08-10 19:41
@markpar Should our paths ever cross in real life, I am owe you a beer!

**Comment by nzcodarnoc** [comment] 2023-12-14 02:05
@markpar praise be your name!

**Comment by antonandreyev** [comment] 2024-02-28 08:20
The solution of using subprojects.afterEvaluate is not working anymore for us after upgrading to RN 73 and Gradle 8.3. It's giving
```
Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
```
Still looking for another way to solve this

**Comment by markpar** [comment] 2024-06-04 22:38
Thank you for the update, @antonandreyev!

**Comment by kprakash2** [comment] 2025-10-22 02:50
Another workaround that worked for me is adding this to the gradle file:

```
androidComponents {
    onVariants(selector().all()) { variant ->
        variant.androidTest?.manifestPlaceholders?.put("auth0Domain", "test-domain")
        variant.androidTest?.manifestPlaceholders?.put("auth0Scheme", "test-scheme")
    }
}

```
