### ISSUE TITLE
Blank screen FB login

### ISSUE THREAD

**Issue by Aleksei-Egorenko-EPAM** [auth0/react-native-auth0#518] opened 2022-09-26 08:34 UTC
RN - 0.61.5
React-native-Auth0 - 2.4.0
device OS - android

User try to login over FB:

    - if user already logged in FB, in webView he see blank screen
    - if user use 1 factor authentication, then after all steps he get “no internet”
    - if user use 2 factor authentication, then after all steps he get blank screen

In all cases webView doesn’t redirect to app and provide jwt

We have not changed our configs for a long time.

A few weeks ago we started to get err_unknown_url_scheme in fb login webView. After that we reattach keystone file in appcenter, that fixed our problem with scheme, but added the new one (described above).

**Comment by poovamraj** [comment] 2022-10-11 19:55
Hi @Aleksei-Egorenko-EPAM I tried to reproduce this issue in versions 2.4.0` and `2.14.0` and was not able to do it. 

Ideally you can try to reproduce this issue in our [sample repository](https://github.com/auth0-samples/auth0-react-native-sample) that way we can figure out whether the issue is on the app side or the configuration side.

**Comment by poovamraj** [comment] 2022-10-17 08:00
Hi @Aleksei-Egorenko-EPAM, please feel free to reach out to us with more details and we will be happy to help. If you have already found a solution, it would be great to share it here so that anyone facing the same issue in future could use this as a reference.

We will close this issue for now but please feel free to reopen it if required.

**Closed by poovamraj** 2022-10-17 08:00 UTC
Labels: question
