### ISSUE TITLE
Android not saving credentials on react native aplication

### ISSUE THREAD

**Issue by cardoso-jv** [auth0/react-native-auth0#577] opened 2022-12-23 15:03 UTC
I'm using the SDK 2.14 to login the user, on iOS side of the application it works perfect, but on the Android side I get this error :

[a0.credential_manager.invalid: No Credentials were previously set.]

when I try to retrieve the credentials on the getCredentials method, is there a reason for it not to save the credentials when I do the authorize process ? ?

**Comment by poovamraj** [comment] 2022-12-26 13:07
Hi, Please try using the latest version (2.16.0). The issue is not reproducible on our end, Can you share the snippet on how you are trying to achieve this?

**Comment by cardoso-jv** [comment] 2022-12-26 13:24
```
 const auth0 = new Auth0({
    domain: Smiles.domain,
    clientId: Smiles.clientId,
  });

  const login = async () => {
    try {
      const login = await authorize({
        scope: Smiles.scope,
        redirect_uri: getRedirectURI(),
      });
      const credentials = await getCredentials(
        Smiles.scope
      );
      const valid = await auth0.credentialsManager.hasValidCredentials();
    } catch (e) {
      console.log(e, 'error');
    }
  };
```

I’m using the 2.16 version now and the error persists, after i try to login multiple times, the credentials are returned normal to me, but in the 4-7 initial times i try to login, it is always returned null with the error mentioned above, the login const is always undefined on both iOS and Android, but the credentials variable come with the info i need on iOS on the first attempt, but on Android only after some time, is there a problem with response time on Android or a initialization time that is bigger for the SDK ?
![Screen Shot 2022-12-26 at 10 22 41](https://user-images.githubusercontent.com/33095675/209553516-459d776d-03fb-4911-ba95-f41cd58b44fa.png)

**Comment by poovamraj** [comment] 2023-01-02 11:24
Hi @cardoso-jv, I tried to reproduce this in our sample app and it is not reproducing for me. I have attached a recording here. Can you try to reproduce this in our [sample repo](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks) and share it to us?

https://user-images.githubusercontent.com/15910425/210224742-f21cfa1e-4fea-4410-aa0b-02cd0ebacf1b.mov

Also, looks like you are using Hooks and Auth0 instance as well, it is not advisable and not check if you have valid credentials, you can check the user object

**Comment by poovamraj** [comment] 2023-01-09 12:42
Hi @cardoso-jv, since this issue is not reproducible on our end, we will close this one until more information is added. Please feel free to reopen it if you have more doubts.

**Closed by poovamraj** 2023-01-09 12:42 UTC
Labels: question, waiting for customer

**Comment by EliasMikula** [comment] 2023-01-21 00:53
Hi @cardoso-jv, I have encountered the same issue.
The problem was that "Token Endpoint Authentication Method" was set to POST.
I changed it to NONE that fixed it for me.

![Settings](https://user-images.githubusercontent.com/48431121/213830115-c3889fd6-d85d-4e8b-8afe-d877bfba7ae2.PNG)

**Comment by kpchoy** [comment] 2023-02-09 19:14
This solution worked for me thanks @EliasMikula !

**Comment by galweiss** [comment] 2023-04-27 14:08
Thanks @EliasMikula. Would suggest to emphasize this point on your documents

**Comment by sm107-uiuc** [comment] 2023-06-21 05:46
Hi @EliasMikula , where do I find this option for a react native app in the auth0 dashboard ? Sorry, I could not seem to find it and I am facing the same issue

**Comment by MxBM** [comment] 2023-07-03 05:17
Were you able to solve your issue? @sm107-uiuc

**Comment by sergsar** [comment] 2024-02-16 12:19
> Hi @cardoso-jv, I have encountered the same issue. The problem was that "Token Endpoint Authentication Method" was set to POST. I changed it to NONE that fixed it for me.
> 
> ![Settings](https://user-images.githubusercontent.com/48431121/213830115-c3889fd6-d85d-4e8b-8afe-d877bfba7ae2.PNG)

Why should it be set to none though and cannot be used in post mode?

**Comment by dennis3124** [comment] 2025-07-03 00:03
Hi all, I am facing the same issue on my Android app. IOS works fine but somehow auth0 is not saving the credentials. Can someone explain why "Token Endpoint Authentication Method" needed to be set to None?
