### ISSUE TITLE
CredentialsManager causes Android app crash

### ISSUE THREAD

**Issue by kunal-shah-firefly** [auth0/react-native-auth0#589] opened 2023-02-01 05:51 UTC
### Describe the problem

Calling `credentialsManager.requireLocalAuthentication()` on app start occasionally causes the following exception for some Android users:

```
java.lang.IllegalStateException: Method addObserver must be called on the main thread
	at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
	at androidx.activity.result.ActivityResultRegistry$LifecycleContainer.addObserver(ActivityResultRegistry.java:455)
	at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:159)
	at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:682)
	at com.auth0.android.authentication.storage.SecureCredentialsManager.requireAuthentication(SecureCredentialsManager.kt:119)
	at com.auth0.react.A0Auth0Module.enableLocalAuthentication(A0Auth0Module.java:109)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:1012)
```

### What was the expected behavior?

App should not crash on initialization for Android users.

### Reproduction

Unfortunately, only a handful of our users have been experiencing this issue and I am not yet able to reproduce. Any initial insight/ideas as to why this could be occurring is appreciated.

### Environment

- **Version of this library used: 2.15.0**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by poovamraj** [comment] 2023-02-02 03:58
Hi @kunal-shah-firefly, I am able to reproduce this issue in our Auth0.Android library which is what react-native-auth0 depends on for Credentials Manager. Looks like forcing `requireAuthentication` method from a bg thread is causing this issue and RN doesn't guarantee that it will be our method call will run on main thread. Running it on main thread would fix it. 

A straight forward fix would be calling runOnUiThread or equivalent in our RNA SDK but we are exploring options to fix it on our Android SDK as well.

**Comment by kunal-shah-firefly** [comment] 2023-02-03 15:22
Hi @poovamraj, thank you for looking into this! Do you have any rough ETA for this fix?

**Comment by poovamraj** [comment] 2023-02-08 13:57
Hi @kunal-shah-firefly, we have a fix for this in PR now. You can track the progress there. We will close this issue now. Please feel free to reopen it if you have more doubts

**Closed by poovamraj** 2023-02-08 13:57 UTC
Labels: bug
