### ISSUE TITLE
Error When Attempting to Reset Password

### ISSUE THREAD

**Issue by nickwelp** [auth0/react-native-auth0#445] opened 2022-01-11 21:07 UTC
When attempting to trigger a reset password flow, I get the following error:
`[SyntaxError: JSON Parse error: Unexpected identifier "We"]`

That is triggered by this bit of code
`    auth0.auth.resetPassword({
        email: username,
        connection: connectionName,
      })`
      
I'm able to create users and log in users, so I believe my settings in Auth0 are correct. 

There error states the issues is line: 158079 │ column: 28, which is this bit of code

`    this.json = function () {
      switch (_this.type) {
        case 'base64':
          return JSON.parse(base64.decode(_this.data));

        case 'path':
          return _fs.default.readFile(_this.data, 'utf8').then(function (text) {
            return Promise.resolve(JSON.parse(text));
          });

        default:
          return JSON.parse(_this.data);
      }
    };`
    
    Thank you

**Comment by nickwelp** [comment] 2022-01-13 20:40
I did work around this, as this particular functionality was fairly easy to do as a fetch without using the library

**Comment by poovamraj** [comment] 2022-01-17 10:04
Thanks a lot @nickwelp. We will check this out and roll out a fix. The description and comment are detailed enough to make it easier for us.

**Comment by poovamraj** [comment] 2022-01-24 16:21
@nickwelp Can you let us know what version of the auth0 library you were using?

**Comment by nickwelp** [comment] 2022-01-24 18:54
^2.9.0

I did some more digging, and I am using a library that may be causing issues, though it works in every other fetch scenario. react-native-blob-util replaces react-native fetch. React-Native fetch is itself a limited implementation of fetch, because it is really JavaScriptCore's XMLHttpRequest with promises wrapped around it. I found an issue with XMLHttpRequest unrelated to Auth0 and used a different fetching library for that reason.  So, I now attribute my issue to using a different fetch library, though oddly the library works for Auth0's library in the other circumstances (creating user, logging in)

**Comment by poovamraj** [comment] 2022-01-24 18:58
Auth0's API response for changing password is a text instead of JSON. I guess this is the reason it is affecting only that API. You can refer to the API Document [here](https://auth0.com/docs/api/authentication?http#change-password). Thanks for bringing this to our notice but since the library is working as intended, we are closing this issue for now. Please feel free to open it if you have more queries

**Closed by poovamraj** 2022-01-24 18:58 UTC
Labels: waiting for customer
