### ISSUE TITLE
auth0.auth.passwordlessWithSMS is not a function

### ISSUE THREAD

**Issue by wincod75** [auth0/react-native-auth0#318] opened 2020-06-18 16:13 UTC
Attempting to setup auth0 passwordless in my RN app, currently getting the error "auth0.auth.passwordlessWithSMS is not a function". Any advice is appreciated.

**Environment**
"react": "16.8.3",
"react-native": "0.59.10",
"react-native-auth0": "1.6.0"

**Code**
import Auth0 from 'react-native-auth0';

const auth0 = new Auth0({
  domain: 'MY_DOMAIN', (placeholder for security)
  clientId: 'MY_ID', (placeholder for security)
});

getLoginCode() {
    this.setState({LogginIn: true});
    auth0.auth
    .passwordlessWithSMS({
      phoneNumber: this.state.phone,
    })
    .then(() => {
      this.setState({codeRequestSent: true});
    })
    .catch(console.error);
  }

<TextInput
    onChangeText={text => this.setState({phone: text})}
    value={this.state.phone}
/>

<TouchableHighlight              
    onPress={() => this.getLoginCode()}
></TouchableHighlight>

**Comment by Widcket** [comment] 2020-06-18 19:05
Hi @wincod75, I just tried `passwordlessWithSMS` in the [sample app](https://github.com/auth0-samples/auth0-react-native-sample) and was not able to reproduce the issue. Will close this one, if you have any further information please comment.

**Closed by Widcket** 2020-06-18 19:05 UTC

**Comment by lbalmaceda** [comment] 2020-06-18 19:39
I see you are using an old version of this library. Passwordless support was added back in `2.2.0`. If you were following the steps on a tutorial we maintain, let us know the URL so we can update it. 

For resolving this try bumping the dependency to the latest version and if you need a solid reference, check the sample app Rita provided above.

**Comment by wincod75** [comment] 2020-06-18 20:00
@lbalmaceda You nailed it, upgraded to 2.2.0 and it's working like charm, thank you!
