### ISSUE TITLE
Expected com.valr.app://auth.valr.com/android/com.valr.app/callback but got https://another_link.here/

### ISSUE THREAD

**Issue by Bardiamist** [auth0/react-native-auth0#283] opened 2020-02-19 02:59 UTC
### Description and Reproduction

If open auth0 WebView then open not Auth0 deep link by app then we have `Expected com.valr.app://auth.valr.com/android/com.valr.app/callback but got https://another_link.here/` error.

Can we to ignore a unexpected links and just to show a dev warning instead error?

### Environment

- **Version of this library used:** 2.3.0

**Comment by Widcket** [comment] 2020-02-19 22:44
Hi @Bardiamist, can you please add detailed reproduction steps for this issue?

**Comment by Bardiamist** [comment] 2020-02-20 02:43
1. Call `auth0.webAuth.authorize`
2. Don't close Auth0 WebView and minimize application
3. Open [universal link](https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/enabling_universal_links) by app

**Comment by Widcket** [comment] 2020-02-27 17:57
Hi @Bardiamist, I wasn't able to reproduce it. Can you share a small app showcasing the issue?
![Screen Recording 2020-02-27 at 14 52 34](https://user-images.githubusercontent.com/5055789/75471723-5c200400-5971-11ea-9d3e-4270913a30ed.gif)

**Comment by Bardiamist** [comment] 2020-02-27 18:09
@Widcket Will that work if you enter login and password?

**Comment by lhuria94** [comment] 2020-03-23 19:12
Hi, @Bardiamist Did you happen to resolve the issue, I am facing the same.

Use case:

1. Have universal linking in use for the application
2. Open auth0 login page
3. Don't close and then go to your email in the background and click on the link which should redirect you to some internal page in your app.
4. Throws: Expected com.valr.app://auth.valr.com/android/com.valr.app/callback but got https://another_link.here/ error.

**Comment by lbalmaceda** [comment] 2020-03-28 13:40
@lhuria94 let's keep that other topic on this other issue, please https://github.com/auth0/react-native-auth0/issues/288.

**Comment by lhuria94** [comment] 2020-03-28 13:51
@lbalmaceda Sure. Thanks :)

**Comment by Widcket** [comment] 2020-03-30 03:10
Closing due to not being able to reproduce. If this is still a problem for you, please ping with a video or app reproducing the issue.

**Closed by Widcket** 2020-03-30 03:10 UTC
Labels: waiting for customer

**Comment by mhautala** [comment] 2023-08-11 11:00
This issue is still valid. The problem in this attempt to reproduce was that the login was not completed: https://github.com/auth0/react-native-auth0/issues/283#issuecomment-592093796

The error comes when callback is handled after succesfull login and webview should close.

**Comment by poovamraj** [comment] 2023-08-16 07:11
@mhautala did you checkout the [migration guide](https://github.com/auth0/react-native-auth0/blob/master/MIGRATION_GUIDE.md) on updating the callback URL
