### ISSUE TITLE
Feature Request - mimic auth0-js api

### ISSUE THREAD

**Issue by rjmontgomery** [auth0/react-native-auth0#296] opened 2020-04-20 17:54 UTC
Hi! 👋, you may remember me from PR #290 where I was talking about some modifications I needed to make in order to support our use case. I was hoping we could possibly contribute back some of our learnings, and possibly improve the library!

To give you some background, we are using both [auth0-js](https://www.npmjs.com/package/auth0-js) and react-native-auth0 to support a cross-platform application that deploys to both web and mobile via react-native-web. For our case there were a few things we had to change in this library in order to have a similar interface between the web/mobile version and thus minimize the code footprint.

This is fairly long, so I am happy to break it into separate issues if that would help you organize!

### Describe the problem you'd like to have solved

  1. breaking up the [webauth.authorize](https://github.com/auth0/react-native-auth0/blob/master/src/webauth/index.js#L58) function into two separate functions - the 
    - the first function performs the fetching of the `access_token` or `code`
    - the second function performs the exchange of the `access_token` for an api token
This would enable it to mimic the functionality of the auth0-js library. And give the client more control over when api tokens are fetched, as in our case we do not always want to immediately fetch the api token.

  2. Adding a `webAuth.logout()` function similar to auth0-js. We are clearing the session on our end, but (and I will admit some ignorance on this part) I am assuming we will want to clear the token from auth0 as well. 

  3. Adding a `checkSession` similar to [the one on auth0-js](https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L549)

### Describe the ideal solution

1. A good solution for this would be to make 2 helper functions and expose them to the client - the first fetches the id token and the second exchanges the id_token for an access token. Then in the `authorize` function you just call the two helper methods. This would enable others to continue using the original `authorize` method, and for users that need more fine grained control we can use the two helper functions.  
Fortunately, you already have both of these functions defined, as you could copy L58 - L97 of the [webauth.authorize](https://github.com/auth0/react-native-auth0/blob/master/src/webauth/index.js#L58) function and extract that into the first helper function. Then take L97 - L108 [client.exchange](https://github.com/auth0/react-native-auth0/blob/master/src/webauth/index.js#L97) and extract that into the second helper function that exchanges you code for an api token. 

2. You could have this be as simple as adding this to the webauth piece
```
  logout(logoutUrl = `https://${this.domain}/v2/logout`, returnTo = callbackUri(this.domain)) {

    const fullLogoutUrl = `${logoutUrl}?clientID=${this.clientId}&returnTo=${returnTo}`

    return this.agent.show(fullLogoutUrl)
  }
```
You may want to swap out the call to the `callbackUri` function, but the core logic is there: just navigate to the logout url in the browser.

3. I'll have to admit some ignorance here as well, and FWIW I haven't actually implemented this on my side yet, but I think it would be good to have in the library as well since it seems reasonable that a client of this library would want to refresh the user's session without requiring the user to re-login.

## Alternatives and current work-arounds

1. Currently we are just removing L97-108 entirely in our fork, since we don't have need for it - our api token provider is actually handled by okta, and while we love auth0 we need to integrate with okta for this piece.

2. I am currently using the code written above to add this functionality myself.

3. None yet, I am still digging into `auth0-js` to figure out how this flow works.

### Additional context

I've already made most of these changes myself, so I am happy to do the legwork of cleaning up my code and making the PR for you provided this is something you are interested in!

Thank you and I greatly appreciate your consideration for some or all of these changes!

**Comment by lbalmaceda** [comment] 2020-04-20 20:44
> 1. breaking up the webauth.authorize function into two separate functions 

This has a huge UX impact. We will definitely not break it, especially because this SDK was designed to interact with Auth0. 

You can call the 2 methods we call internally yourself and have your own custom _webauth_ implementation, by using the methods provided in the `auth` package just like we do. If I understand correctly, this is what you're doing today. 

> 2. Adding a webAuth.logout() function similar to auth0-js

I'm not familiar with how auth0js performs the logout. I assume its calling the Auth0 logout endpoint. That means that the Auth0 login page will forget who you are, clearing the browser cookie. Optionally, you could also pass the "federated"  parameter. This will attempt to also call the logout endpoint of your identity provider, i.e. Google. The idea is that after a call to this endpoint you are at least asked for your password.

But since this SDK doesn't store any tokens for you, it is up to the developer to remove those tokens from the storage once the user decides to "log out".

> 3. Adding a checkSession

I'm not sure if this is a valid flow to be called from a Native client like a mobile app. But you do have the alternative of using refresh tokens. 

There's a [method](https://github.com/auth0/react-native-auth0/blob/master/src/auth/index.js#L205) you can call to exchange the one you were given originally for fresh tokens. Of course, you'll have to keep the refresh token somewhere safe and control the expiration of the tokens you have so you know when you'll need new tokens and refresh them in advance.

**Comment by rjmontgomery** [comment] 2020-04-20 21:18
Good points all around, and you'll have to forgive me my ignorance on some of these items. Feel free to close the issue, but if you are willing to humor me a bit longer I do have a final question out of personal curiosity.

> This has a huge UX impact

Can you help me understand what you mean by this? My solution would look something like this
```
   authorize(...) {
      fetchAccessToken(...)
      exchange(...)
   }
   fetchAccessToken(...) {...}
   exchange(...) {...}
```
Is the thought that by exposing more than just the `authorize` method on the webauth class might confuse users about which method to use?

**Comment by lbalmaceda** [comment] 2020-04-20 21:46
I mentioned UX because the `webauth.authorize` method today calls those 2 requests for the user automatically, versus having the user handle that interaction manually. It even hooks in the [validation of the ID token](https://github.com/auth0/react-native-auth0/blob/master/src/webauth/index.js#L100), which is really necessary when you are consuming its contents locally.

But remember, the 2 methods that we call on `webauth.authorize` are already public and available for you to call [here](https://github.com/auth0/react-native-auth0/blob/master/src/auth/index.js#L44) and [here](https://github.com/auth0/react-native-auth0/blob/master/src/auth/index.js#L101). I don't follow you on how changing the webauth class would help your use case.

You also mentioned not needing to obtain an access token with an audience for calling your API right away. That's fine, but as soon as you need that, you will still need to go through the same steps again. You will need to authenticate this time passing the `audience` value of your API. Unless.. you want to save that step and login once keeping that access token with the audience you'll require later, even if you don't require to use it right away. Does that make sense?

Looking forward to your comments,

**Comment by rjmontgomery** [comment] 2020-04-20 22:05
Yes that really cleared things up! Thank you! 

It seems I may have misunderstood what `webauth.authorize` is doing even in my use case (and admittedly I am still somewhat new to javascript). It seems you have actually implemented my use case exactly without me realizing it. 

> you want to save that step and login once keeping that access token with the audience you'll require later

If I understand you correctly this is in fact what our application is doing now.

**Comment by rjmontgomery** [comment] 2020-04-20 22:06
Really appreciate you taking the time to explain this for me! You all are doing great work!

**Comment by lbalmaceda** [comment] 2020-04-20 22:28
> We store the token that we would get back from that .authorizeUrl function and then use that to request an API token with new audiences etc from okta.

That's not good...  Only consume the tokens from the second response (the code exchange). The access token you receive in the first request should be discarded.

There are different authentication flows depending on the application type you're calling the API from. There are some red flags you want to avoid, such as doing an implicit-flow from a native application (as it seems you are doing now). Native applications typically perform `Code Auth + PKCE` and verify the ID token. That's what this SDK does in that two-steps method. 

If you want to dig deeper, read more about flows here https://auth0.com/docs/flows.

**Comment by rjmontgomery** [comment] 2020-04-20 22:53
> That's not good... Only consume the tokens from the second response (the code exchange). The access token you receive in the first request should be discarded.

Seems like I need to do some more research on my end - appreciate the docs link I definitely want to do some more digging on this. And also appreciate you bringing up this issue - I'll make sure that gets resolved as well.

Thanks! I'll check out those docs!

**Comment by lbalmaceda** [comment] 2020-04-21 15:13
Closing this for now. If you run into issues, please re-open.

**Closed by lbalmaceda** 2020-04-21 15:13 UTC
Labels: waiting for customer
