### ISSUE TITLE
TimeoutError when logging in

### ISSUE THREAD

**Issue by jnalviano** [auth0/react-native-auth0#514] opened 2022-09-09 18:26 UTC
### Describe the problem

A number of our users have been experiencing what we believe is a bug in the Auth0 SDK in our app. When a user tries signing in using the universal login widget, login appears to succeed: the app callback URL is successfully hit, returning the user to our app and Auth0 logs show a successful signup. However, the user experiences login failing and is unable to authenticate into our app. We see a `TimeoutError` occurring in your SDK when calling `auth0.webAuth.authorize`, causing this method to fail here: https://github.com/auth0/react-native-auth0/blob/6a9d257bb2e96b7ec1e70928944d546398827960/src/utils/fetchWithTimeout.js.

For most users who have experienced this, creating a new Auth0 user for them and linking it to their app account has allowed them to successfully log in. However, for several users, this workaround only helps for one login before the user experiences this behavior all over again with the new account. We've also already reported this issue to Auth0's support.

### What was the expected behavior?

We expect the react native SDK's behavior to match the response from Auth0. I.e. if the login was successful, the SDK should successfully authenticate the user and redirect them to our app without timing out.

### Reproduction

So far we have been unable to reproduce this behavior ourselves, but the number of reported cases has continued to increase.

### Environment

- **Version of this library used:** `2.10.0`
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by musab-olurode** [comment] 2022-09-15 08:08
@jnalviano I seem to be experiencing the same issue (only on my emulator in my case). Every other android device works fine.

**Comment by poovamraj** [comment] 2022-09-15 16:44
@jnalviano this looks really peculiar. 

>  However, the user experiences login failing and is unable to authenticate into our app.

Can you let me know if there is any error message available at this point?

Also when you mention the signup is successful, do you get the access token?

The only thing that happens after being redirected to the app and before getting the access token is PKCE network call. Will u be able to confirm if the error is happening there?

**Comment by fractalframing** [comment] 2022-09-15 23:01
> @jnalviano I seem to be experiencing the same issue (only on my emulator in my case). Every other android device works fine.

That's interesting it's happening to me too. If I copy the request (by debugging this library's code)  and send it via Postman I receive the appropriate token. On the Android simulator however, I receive a `Timeout error` and no other info. This is for both my project (`React Native v0.70`) and the examples provided in this repo configured to point towards my Auth0 endpoint. 
I'll test on a physical device and a clean emulator and report back the results. 
For me, logging in works just fine and redirects back to the app but the app hangs in the login screen and never gets the access credentials just the timeout error.

**Comment by poovamraj** [comment] 2022-10-11 19:05
Hey all, If the issue is only in the emulator, can you confirm the time in the emulator is not way off? Currently RN's fetch API doesn't provide a lot of information to debug this and we are not able to reproduce this issue on our end (Both on emulator or physical device). 

Is there any steps that you can mention to make this reproducible if the issue is not with the device time

**Comment by poovamraj** [comment] 2022-10-17 07:58
Hi @fractalframing @musab-olurode @jnalviano Hope the above solution helps. I will close this issue for now but please feel free to reopen it if you have any more doubts

**Closed by poovamraj** 2022-10-17 07:58 UTC
Labels: waiting for customer

**Comment by raichshlv** [comment] 2022-11-03 19:40
Hi, same thing just started happening, however for me this is happening on a **physical device**.
Everything was working as expected yesterday but today it started producing the same issue as mentioned previously.
The popup opens for a second, then closes and after a while the timeout error thrown by `fetchWithTimeout()` appears.

Clock on the device seems to be correct.

After doing `webAuth.clearSession()` I am able to view the login page. After logging in the popup closes and then the timeout error throws once more.

React Native 0.70.4
Package v2.14.1

**Comment by walterholohan** [comment] 2022-11-08 19:25
I've managed to reproduce the Timeout error when using Google and Facebook web auth. It occurs when a user has to enter 2FA with their social provider i.e. enter a 2FA which would require them to navigate away from the app and open up an app like Authenticator to get the 6-digit code. They then go back to the app, enter the 2FA code and finish the authentication flow which completes successfully. However the API `await auth0.webAuth.authorize()` will throw the `Timeout` error instead of returning the accessToken. 

Is there a way of increasing the timeout value?

**Comment by walterholohan** [comment] 2022-11-08 19:26
@poovamraj can we re-open this issue please?

**Comment by xanderdeseyn** [comment] 2022-12-13 15:08
Any progress on this? Multiple users are experiencing this as well in our app.

**Comment by poovamraj** [comment] 2022-12-13 16:32
Hi, @xanderdeseyn @walterholohan can you provide a sample app (Github repo) which reproduces the issue? We are quite not able to reproduce this on our end and each issue reported here seems to be a very different case from another.

**Comment by kmesic** [comment] 2023-03-22 01:42
Our app is also running into a lot of Timeout errors in our prod logs. And we very rarely are able to reproduce. Mostly occurring when we refresh tokens. Based on the logs, it looks like the timeout is not waiting the default 10s.

Could we add a feature to allow consumers to opt out of the timeout logic? This would allow consumers to implement their own timeout logic if they want.
