### ISSUE TITLE
auth0.webAuth.authorize sometimes does not resolve and hangs

### ISSUE THREAD

**Issue by aprilmintacpineda** [auth0/react-native-auth0#357] opened 2021-02-03 06:34 UTC
### Describe the problem

We have a login screen that has a "Login" button on it, when you press the button it fires the following codes:

```js
const auth0 = new Auth0({ domain, clientId });

function onPress () {
  // hangs in here forever
  const credentials = await auth0.webAuth.authorize(
    {
      scope:
        'openid profile email read:current_user offline_access',
      connection: 'Username-Password-Authentication'
    },
    {
      ephemeralSession: true
    }
  );

  // doesn't get executed
  console.log(credentials);
}
```

For some unknown reasons, After the user has logged in, the login page just gets stuck there but I can see "successful login" on the logs, the callee just doesn't return to the caller, so I don't see the console log, I also don't see any errors or any logs at all.

It only happens on android, in ios it works fine, I'm thinking that it has something to do with the configuration rather than the code itself?

### What was the expected behavior?

I expect the promise to resolve.

### Reproduction

- Step 1..
- Step 2..
- ...

Not really sure how to replicate it, although we do have two accounts, the device originally uses `account1` it has been using that for a while, then we switched to `account2`, that's when this happened, I have uninstalled the app, cleared data, `./gradlew clean`, etc.

### Environment

- **Version of this library used:** 2.7.0
- **Which framework are you using, if applicable:** n/a
- **Other modules/plugins/libraries that might be involved:** n/a
- **Any other relevant information you think would be useful:** All given above

**Comment by Widcket** [comment] 2021-02-05 15:05
@lbalmaceda can you please take a look?

**Comment by lbalmaceda** [comment] 2021-02-05 15:49
If I understand correctly, what you are saying is that the redirection from the browser into your application is broken for the Android platform. If that worked for the tenant `account1` and stopped working with `account2` is definitely a configuration issue. 

You'd need to check in the Auth0 dashboard that you are using an application of type "Native" and registering the allowed URLs correctly. Follow this section of the readme https://github.com/auth0/react-native-auth0#callback-urls.

You should also check that the `AndroidManifest.xml` file of your android application is declaring the intent-filter with the right values (package/application id) and Auth0 domain. These need to match the URLs you allowed above in the dashboard. 

Finally, check that when you are instantiating the `Auth0` object you are passing the same client ID and domain values that appear on the dashboard:

```
const auth0 = new Auth0({
  domain: '{YOUR_AUTH0_DOMAIN}',
  clientId: '{YOUR_CLIENT_ID}',
});
```

**Comment by aprilmintacpineda** [comment] 2021-02-07 22:12
Thanks, I will try these out.

**Comment by aprilmintacpineda** [comment] 2021-02-07 22:57
> You should also check that the AndroidManifest.xml file of your android application is declaring the intent-filter with the right values (package/application id) and Auth0 domain. These need to match the URLs you allowed above in the dashboard.

Aha, that solved it, I forgot to change the `android:host`. 

Thanks for the kind resposne 🙇🏻

**Comment by aprilmintacpineda** [comment] 2021-08-24 06:30
I'm reopening this to ask for and guidance, this time it happens when using the latest version 2.9.0 and only happens on android.

On my `build.gradle`, I have:

```
manifestPlaceholders = [
    auth0Domain: project.env.get("AUTH0_DOMAIN"),
    auth0Scheme: "${applicationId}"
]
```

I am able to login but for some reason after logging in, and I can see logs in auth0 logs but the login screen just stays put and nothing happens afterward.

This was the call to login

```
const credentials = await auth0.webAuth.authorize(
  {
    scope:
      'openid profile email read:current_user offline_access',
    connection: 'Username-Password-Authentication',
    audience,
    prompt: 'login'
  },
  {
    ephemeralSession: true
  }
);
```

**Comment by Widcket** [comment] 2021-08-24 13:00
Hi @aprilmintacpineda, in your merged manifest, do the SDK's RedirectActivity and AuthenticationActivity appear declared? Does the intent filter show up, and does its URL match the one you configured as the Callback and Logout URL in the Auth0 dashboard?

**Comment by aprilmintacpineda** [comment] 2021-08-25 06:23
> in your merged manifest, do the SDK's RedirectActivity and AuthenticationActivity appear declared?

I don't know how to check this.

> Does the intent filter show up, and does its URL match the one you configured as the Callback and Logout URL in the Auth0 dashboard?

I have checked the callback and logout URLs and so far I think they are all correct.

> Does the intent filter show up

I don't know what exactly you mean by this.

This is what happens, I do:

```js
const credentials = await auth0.webAuth.authorize(
  {
    scope:
      'openid profile email read:current_user offline_access',
    connection,
    audience: 'https://tscoaaewapapi-data01.azurewebsites.net/',
    prompt: 'login'
  },
  {
    ephemeralSession: true
  }
);

console.log('credentials', credentials); // this will never be executed
```

When the user pressed a button, then the login screen actually appears, and I can type and if I type the wrong password it works as expected, but when I type the correct credentials, after successful login, the login screen does not fade and it does not return the control to the app, it just hangs there. If I check the logs on auth0 dashboard, I can see login success log so it means it's able to login successfully, it's just that the callback doesn't get called.

After some more trial-and-error, I finally found the problem.

So we use:

```gradle
flavorDimensions "version"
productFlavors {
    dev {
        applicationIdSuffix ".dev"
    }
    staging {
        applicationIdSuffix ".staging"
    }
    production {}
}
```

I tried hardcoding them:

```gradle
manifestPlaceholders = [
    auth0Domain: project.env.get("AUTH0_DOMAIN"),
    auth0Scheme: "com.myapp.dev"
]
```

and it worked vs:

```gradle
manifestPlaceholders = [
    auth0Domain: project.env.get("AUTH0_DOMAIN"),
    auth0Scheme: "${applicationId}"
]
```

**Comment by Widcket** [comment] 2021-08-25 14:07
> I don't know how to check this.

You can check that from Android studio, to see if the [merged manifest](https://android-doc.github.io/tools/building/manifest-merge.html) contains everything the SDK expects it to contain:

<img width="1364" alt="Screen Shot 2021-08-25 at 11 00 27" src="https://user-images.githubusercontent.com/5055789/130805225-c954e2bf-0850-4e78-bd26-9dd86514729d.png">

> So I think it's the applicationId, it's not able to resolve it with applicationIdSuffix

Yes, we added a bit to the README about product flavors:

<img width="880" alt="Screen Shot 2021-08-25 at 10 58 48" src="https://user-images.githubusercontent.com/5055789/130805614-aef525ec-a7b8-4e3f-a480-ef019bcc78a0.png">

I'll close this issue, as you've found the cause of the problem. Please ping if you'd like to reopen.

**Closed** 2021-08-25 14:09 UTC
Labels: waiting for customer
