### ISSUE TITLE
No callback issue

### ISSUE THREAD

**Issue by alexandrzavalii** [auth0/react-native-auth0#47] opened 2017-06-18 15:56 UTC
Sorry for opening many issues, but since you closed the previous one, I had to open it again :D

I had to add quick workaround to receive back the callback. I added setTimeout.

Maybe there is a better solution ?

https://github.com/auth0/react-native-auth0/blob/master/networking/index.js

```
    return fetch(url, options)
      .then((response) => {
        const payload = { status: response.status, ok: response.ok, headers: response.headers };
        setTimeout(() => null, 0); <!--- quick fix which solves the promise issue ---->
        return response.json()
          .then((json) => {
            return { ...payload, json };
          })
          .catch(() => {
            return response.text()
              .then((text) => {
                return { ...payload, text };
              })
              .catch(() => {
                return { ...payload, text: response.statusText };
              });
          });
      });
```

**Comment by hzalaz** [comment] 2017-06-18 16:04
Can you build a sample gh repo I can see why it's not calling the callback?. On my end it's working with a bare bones app that only has auth0

**Comment by cocojoe** [comment] 2017-06-19 11:49
@alexandrzavalii You might want to check out a preview chapter one of the sample code for hosted login.  
https://github.com/auth0-samples/auth0-react-native-sample

I have tested in both iOS and Android with no issues.

**Comment by hzalaz** [comment] 2017-07-06 02:22
@alexandrzavalii any news?

**Comment by hzalaz** [comment] 2017-08-21 22:19
Cannot reproduce it so closing it. Please add more info if its still happening

**Closed by hzalaz** 2017-08-21 22:19 UTC
Labels: F0: more info needed
