### ISSUE TITLE
The login did not redirect on Android despite a successful login.

### ISSUE THREAD

**Issue by ysheep-js** [auth0/react-native-auth0#704] opened 2023-08-16 07:17 UTC
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Every things works perfectly on IOS. However, on Android, there's an issue where it fails to redirect to the app after a successful login. The error message displayed is as follows:
![image](https://github.com/auth0/react-native-auth0/assets/65909463/e3eaa501-daad-4ee6-a3d5-16cc4adb5634)

### Reproduction

See README

### react-native-auth0 version

3.0.0

### React Native version

0.71.8

### Expo version

48.0.18

### Platform

Android

### Platform version(s)

any

**Comment by poovamraj** [comment] 2023-08-16 07:27
@ysheep-js This is because you haven't updated the AndroidManifest.xml to this

`manifestPlaceholders = [auth0Domain: "YOUR_AUTH0_DOMAIN", auth0Scheme: "${applicationId}.auth0"]`

The .auth0 prefix needs to be added here as well. Can you do try that and let me know?

We can document it properly to avoid confusion.

**Comment by ysheep-js** [comment] 2023-08-16 07:56
> @ysheep-js This is because you haven't updated the AndroidManifest.xml to this
> 
> `manifestPlaceholders = [auth0Domain: "YOUR_AUTH0_DOMAIN", auth0Scheme: "${applicationId}.auth0"]`
> 
> The .auth0 prefix needs to be added here as well. Can you do try that and let me know?
> 
> We can document it properly to avoid confusion.

I have add this code in `build.gradle`:
`manifestPlaceholders = [auth0Domain: "https://xxx.us.auth0.com", auth0Scheme: "com.xxxx.auth0"]`
But in `AndroidManifest.xml` there is no manifestPlaceholders.

**Comment by poovamraj** [comment] 2023-08-16 07:56
Sorry it should have been build.gradle. I have updated the comment. Is it working for you now?

**Comment by poovamraj** [comment] 2023-08-16 07:58
Did you try installing the app again? Any changes to native code you have to install the app fresh. You can try uninstalling and installing the app again

**Comment by ysheep-js** [comment] 2023-08-16 08:07
I've gone through several reinstallations on the Pixel_4_API_33 simulator, but the issue persists. I've also cleared the cached data on the simulator.

**Comment by poovamraj** [comment] 2023-08-16 08:10
Can you run this command and let me know the results you get for your package name

`adb shell dumpsys package r`

**Comment by poovamraj** [comment] 2023-08-16 08:16
Also the callback URL you have on your dashboard

**Comment by ysheep-js** [comment] 2023-08-16 08:23
Here are the result of `adb shell dumpsys package r`
<img width="915" alt="image" src="https://github.com/auth0/react-native-auth0/assets/65909463/de2c58ac-fd27-49e1-b989-a7a5acaf1d32">
The callback URL on dashboard is: 
com.userly.aimultichat.auth0://whis-chat-dev.us.auth0.com/ios/com.userly.aimultichat/callback, com.userly.aimultichat.auth0://whis-chat-dev.us.auth0.com/android/com.userly.aimultichat/callback

**Comment by poovamraj** [comment] 2023-08-16 08:28
@ysheep-js you should have used grep for your package name instead of package. The grep should be for `com.userly.aimultichat`

I am not able to see the information for your application here.

**Comment by ysheep-js** [comment] 2023-08-16 08:29
OK, here is the result: 
<img width="813" alt="image" src="https://github.com/auth0/react-native-auth0/assets/65909463/70eb79ce-06bf-45f8-b7cf-3352afe5cd7c">

**Comment by poovamraj** [comment] 2023-08-16 08:37
@ysheep-js I'd suggest you share your app.json and also try running `npx expo prebuild --clean` as mentioned in the migration guide.

**Comment by ysheep-js** [comment] 2023-08-16 08:44
Here is my app.json:
`{
    "expo": {
    "name": "NexMate",
    "slug": "ai-multi-chat",
    "version": "1.0.4",
    "orientation": "portrait",
    "icon": "./src/assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./src/assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#1B1B26"
    },
    "assetBundlePatterns": [
      "**/*",
      "src/public/**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.userly.aimultichat"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./src/assets/images/adaptive-icon.png",
        "backgroundColor": "#1B1B26"
      },
      "package": "com.userly.aimultichat"
    },
    "web": {
      "bundler": "metro",
      "favicon": "./src/assets/images/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "330f7d1a-4be2-465a-b1ab-fad13e6ffc71"
      }
    },
    "plugins": [
        [
            "react-native-auth0",
            {
                "domain": "whis-chat-dev.us.auth0.com"
            }
        ]
    ]
  }
}
`
I have tried `npx expo prebuild --clean` actually but not works.

**Comment by poovamraj** [comment] 2023-08-16 10:09
@ysheep-js I am not able to reproduce this issue. Can you try and reproduce it in our sample repo here - https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Expo? If so you can share the repo without sensitive info and we can take it from there.

**Comment by felipem292** [comment] 2023-08-16 23:10
i'm having the same problem with a new project android does not redirect after loggin
 "dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-auth0": "^3.0.1"
  },
  
  i don't have more packages installed

**Comment by ysheep-js** [comment] 2023-08-17 02:36
> @ysheep-js I am not able to reproduce this issue. Can you try and reproduce it in our sample repo here - https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Expo? If so you can share the repo without sensitive info and we can take it from there.

I've noticed that when using sample repository, everything works perfectly. However, I've come to realize that there might be an issue with my app.config.ts file. Here's the code snippet from that file:
`import { ExpoConfig, ConfigContext } from 'expo/config';

export default ({ config }: ConfigContext): ExpoConfig => ({
    ...config,
    name: 'xxx',
    slug: 'ai-multi-chat',
    plugins: [
        [
            'react-native-auth0',
            {
                domain: process.env.EXPO_PUBLIC_AUTH0_DOMAIN || 'https://xxx.auth0.com',
            },
        ],
    ],
});`
Interestingly, I also have an app.json and an app.config.ts file because I need to configure different Auth0 domains using the process.env.EXPO_PUBLIC_AUTH0_DOMAIN environment variable. However, when I removed the app.config.ts file, the application started working correctly. I'm uncertain about the exact issue causing this behavior, though.

Could you please help me understand what might be going wrong?

**Comment by poovamraj** [comment] 2023-08-17 12:00
@ysheep-js I am not sure as I don't have the full context. Happy that it is working for you and the SDK seems to be working as intended. We will close this issue now. Please feel free to comment here and we can reopen this issue if required.

**Closed by poovamraj** 2023-08-17 12:00 UTC
Labels: bug

**Comment by felipem292** [comment] 2023-08-17 14:02
@poovamraj  but what happen if i'm not using expo just CLI do you have any solution?

**Comment by VilleMiekkoja** [comment] 2024-01-11 21:29
Have the same problem but with just the CLI, no luck so far.
