### ISSUE TITLE
Can't access refreshToken on React Native

### ISSUE THREAD

**Issue by serp1412** [auth0/react-native-auth0#598] opened 2023-02-23 01:25 UTC
### Describe the problem
We're trying to integrate auth0 for our apps and authorization works well, however when trying to get the refreshToken to allow quiet reauthnetication for our users, it keeps failing authorization itself. i.e. the whole `getCredentials` response is undefined.

### What was the expected behavior?
We're expecting that after going through the authorization flow, with proper setup, both `refreshToken` and `accessTokens` would  contain proper values.

### Reproduction

- Login code:
```
      await clearCredentials()
      await authorize({ audience: 'our-audience', scope: 'offline_access' })
      const { accessToken, refreshToken } = await getCredentials()
      console.log('refreshToken ==========', refreshToken)
```

Without the `offline_access` scope authorization works well but `refreshToken` is null
With that scope added, authorization fails entirely and throws: 
`[TypeError: undefined is not an object (evaluating '_yield$getCredentials.accessToken')]`

- Allow Offline Access in the Api settings set to On
- Refresh Token Rotation enabled in the application settings

### Environment

"react": "18.2.0",
"react-native": "0.68.5",
"react-native-auth0": "^2.16.0",

**Comment by poovamraj** [comment] 2023-02-27 10:33
Hi @serp1412 this sure does seem new. Since it is not reproducible on our end, can you reproduce this in our [sample app](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks) and share it?

**Comment by serp1412** [comment] 2023-03-01 00:12
hey @poovamraj, thanks for getting back to me, we've figured it out. Although we're not 100% sure what fixed it, we're thinking the reason has to do with this: https://community.auth0.com/t/failed-exchange-feacft-until-the-client-is-saved-through-auth0-dashboard-manually/51264

**Comment by poovamraj** [comment] 2023-03-01 08:56
Sounds great @serp1412. We will close this issue now.

**Closed by poovamraj** 2023-03-01 08:56 UTC
Labels: waiting for customer, needs investigation
